import crypto from "node:crypto";

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const DIGEST = /^[0-9a-f]{64}$/;
const TIME = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/;
const SAFE_NAME = /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/;
const SECRET = /(secret|token|password|private.?key|api.?key|authorization|cookie|credential)/i;
const MAX = { string: 4096, array: 64, document: 64 * 1024 };
const schemas = {
  appManifest: { version: 1, kind: "agentpass.app-manifest" },
  sourceBundleStatement: { version: 1, kind: "agentpass.source-bundle" },
  buildReceipt: { version: 1, kind: "agentpass.build-receipt" },
  publishPlan: { version: 1, kind: "agentpass.publish-plan" },
  applicationGrant: { version: 1, kind: "agentpass.application-grant" },
  deploymentReceipt: { version: 1, kind: "agentpass.deployment-receipt" },
  providerOperation: { version: 1, kind: "agentpass.provider-operation" },
  providerResult: { version: 1, kind: "agentpass.provider-result" }
};

export class SmallSoftwareContractError extends TypeError {
  constructor(issues) { super(issues.map((x) => `${x.path}: ${x.code}`).join("; ")); this.name = "SmallSoftwareContractError"; this.code = "ERR_SMALL_SOFTWARE_CONTRACT"; this.issues = Object.freeze(issues); }
}
const issue = (path, code) => ({ path, code });
function object(value, path) { if (!value || typeof value !== "object" || Array.isArray(value)) throw new SmallSoftwareContractError([issue(path, "object_required")]); return value; }
function keys(value, allowed, path, out) { for (const key of Object.keys(value)) if (!allowed.includes(key)) out.push(issue(`${path}.${key}`, "unknown_field")); }
function required(value, names, path, out) { for (const key of names) if (!(key in value)) out.push(issue(`${path}.${key}`, "required")); }
function str(value, path, out, { max = MAX.string, pattern, secret = true } = {}) { if (typeof value !== "string" || value.length === 0 || Buffer.byteLength(value) > max) { out.push(issue(path, "invalid_string")); return; } if (/[\u0000-\u001f\u007f]/.test(value)) out.push(issue(path, "control_character")); if (pattern && !pattern.test(value)) out.push(issue(path, "invalid_format")); if (secret && (SECRET.test(path) || /-----BEGIN (?:RSA |EC )?PRIVATE KEY-----|(?:sk_live_|ghp_|xoxb-|AKIA[0-9A-Z]{16})/.test(value))) out.push(issue(path, "secret_like_value")); }
function id(value, path, out) { str(value, path, out, { max: 36, pattern: UUID, secret: false }); }
function digest(value, path, out) { str(value, path, out, { max: 64, pattern: DIGEST, secret: false }); }
function time(value, path, out) { str(value, path, out, { max: 24, pattern: TIME, secret: false }); if (typeof value === "string" && TIME.test(value) && Number.isNaN(Date.parse(value))) out.push(issue(path, "invalid_time")); }
function arr(value, path, out, each) { if (!Array.isArray(value) || value.length > MAX.array) { out.push(issue(path, "invalid_array")); return; } value.forEach((v, i) => each(v, `${path}[${i}]`, out)); }
function relPath(value, path, out) { str(value, path, out, { max: 512, secret: false }); if (typeof value === "string" && (value.startsWith("/") || value.includes("\\") || value.split("/").includes("..") || value.split("/").some((x) => x === "" || x === "."))) out.push(issue(path, "unsafe_path")); }
function origin(value, path, out) { str(value, path, out, { max: 256, secret: false }); try { const u = new URL(value); if (u.protocol !== "https:" || u.username || u.password || u.pathname !== "/" || u.search || u.hash) out.push(issue(path, "invalid_origin")); } catch { out.push(issue(path, "invalid_origin")); } }
function finish(value, errors, path) { if (JSON.stringify(value).length > MAX.document) errors.push(issue(path, "document_too_large")); if (errors.length) throw new SmallSoftwareContractError(errors); return deepFreeze(value); }
function deepFreeze(v) { if (v && typeof v === "object") { Object.freeze(v); Object.values(v).forEach(deepFreeze); } return v; }
function base(input, spec, allowed, requiredNames) { const v = object(input, "$"); const e = []; keys(v, allowed, "$", e); required(v, requiredNames, "$", e); if (v.version !== spec.version) e.push(issue("$.version", "unsupported_version")); if (v.kind !== spec.kind) e.push(issue("$.kind", "invalid_kind")); return [v, e]; }
function common(input, spec, allowed, requiredNames) { const [v, e] = base(input, spec, allowed, requiredNames); id(v.organization_id, "$.organization_id", e); id(v.app_id, "$.app_id", e); return [v, e]; }

export function normalizeAppManifest(input) { const [v,e]=base(input,schemas.appManifest,["version","kind","name","runtime","entrypoint","static_assets","data","egress","connections","schedules","health_path"],["version","kind","name","runtime","entrypoint"]); str(v.name,"$.name",e,{max:128,pattern:SAFE_NAME,secret:false}); if(v.runtime!=="cloudflare-worker")e.push(issue("$.runtime","unsupported_runtime")); relPath(v.entrypoint,"$.entrypoint",e); if(v.static_assets!==undefined)relPath(v.static_assets,"$.static_assets",e); if(v.health_path!==undefined){str(v.health_path,"$.health_path",e,{max:256,secret:false});if(typeof v.health_path==="string"&&(!v.health_path.startsWith("/")||v.health_path.includes("..")))e.push(issue("$.health_path","invalid_path"));} arr(v.data??[],"$.data",e,(x,p,a)=>{object(x,p);keys(x,["name","kind","migration_dir"],p,a);str(x.name,`${p}.name`,a,{max:128,pattern:SAFE_NAME,secret:false});if(x.kind!=="isolated_sql")a.push(issue(`${p}.kind`,`unsupported_data_kind`));if(x.migration_dir!==undefined)relPath(x.migration_dir,`${p}.migration_dir`,a)}); arr(v.egress??[],"$.egress",e,(x,p,a)=>{object(x,p);keys(x,["origin","methods"],p,a);origin(x.origin,`${p}.origin`,a);arr(x.methods,`${p}.methods`,a,(m,mp,aa)=>str(m,mp,aa,{max:16,pattern:/^[A-Z]+$/,secret:false}))}); arr(v.connections??[],"$.connections",e,(x,p,a)=>{object(x,p);keys(x,["name","kind"],p,a);str(x.name,`${p}.name`,a,{max:128,pattern:SAFE_NAME,secret:false});if(x.kind!=="managed")a.push(issue(`${p}.kind`,`unsupported_connection_kind`));}); arr(v.schedules??[],"$.schedules",e,(x,p,a)=>{object(x,p);keys(x,["name","cron"],p,a);str(x.name,`${p}.name`,a,{max:128,pattern:SAFE_NAME,secret:false});str(x.cron,`${p}.cron`,a,{max:128,secret:false});}); return finish(v,e,"$"); }
export function normalizeSourceBundleStatement(input) { const [v,e]=common(input,schemas.sourceBundleStatement,["version","kind","organization_id","app_id","project_id","agent_session_id","device_id","git_commit","dirty_tree_digest","file_merkle_root","ignore_policy_version","file_inventory_digest","manifest_digest","lockfile_digests","total_bytes","scanner_version","redacted_findings","created_at","expires_at"],["version","kind","organization_id","app_id","project_id","agent_session_id","device_id","file_merkle_root","manifest_digest","total_bytes","created_at","expires_at"]); for(const k of ["project_id","agent_session_id","device_id"])id(v[k],`$.${k}`,e); for(const k of ["git_commit","dirty_tree_digest","file_merkle_root","file_inventory_digest","manifest_digest"])if(v[k]!==undefined)digest(v[k],`$.${k}`,e); for(const k of ["created_at","expires_at"])time(v[k],`$.${k}`,e); if(typeof v.total_bytes!=="number"||!Number.isSafeInteger(v.total_bytes)||v.total_bytes<0||v.total_bytes>1024*1024*1024)e.push(issue("$.total_bytes","invalid_size")); arr(v.lockfile_digests??[],"$.lockfile_digests",e,(x,p,a)=>digest(x,p,a)); arr(v.redacted_findings??[],"$.redacted_findings",e,(x,p,a)=>{str(x,p,a,{max:256,secret:false})}); return finish(v,e,"$"); }
export function normalizeBuildReceipt(input) { const [v,e]=common(input,schemas.buildReceipt,["version","kind","organization_id","app_id","release_id","source_bundle_digest","builder_image_digest","sandbox_instance_id","build_command","toolchain_versions","lockfile_digest","sbom_digest","artifact_digest","asset_inventory_digest","scanner_results_digest","preview_deployment_id","started_at","finished_at","result"],["version","kind","organization_id","app_id","release_id","source_bundle_digest","builder_image_digest","sandbox_instance_id","artifact_digest","started_at","finished_at","result"]); id(v.release_id,"$.release_id",e); id(v.sandbox_instance_id,"$.sandbox_instance_id",e); if(v.preview_deployment_id!==undefined)id(v.preview_deployment_id,"$.preview_deployment_id",e); for(const k of ["source_bundle_digest","builder_image_digest","lockfile_digest","sbom_digest","artifact_digest","asset_inventory_digest","scanner_results_digest"])if(v[k]!==undefined)digest(v[k],`$.${k}`,e); for(const k of ["started_at","finished_at"])time(v[k],`$.${k}`,e); str(v.result,"$.result",e,{max:32,pattern:/^(succeeded|failed)$/ ,secret:false}); if(v.build_command!==undefined){arr(v.build_command,"$.build_command",e,(x,p,a)=>str(x,p,a,{max:256,secret:false}))} return finish(v,e,"$"); }
export function normalizePublishPlan(input) { const [v,e]=common(input,schemas.publishPlan,["version","kind","organization_id","app_id","release_id","source_bundle_digest","build_receipt_digest","artifact_digest","preview_deployment_id","audience","app_roles","lifetime_seconds","retention_seconds","ingress","data","egress","schedules","runtime","resource_ceiling","cost_ceiling","policy_version","authority_delta","approval_required","risk_classification","created_at","expires_at"],["version","kind","organization_id","app_id","release_id","source_bundle_digest","build_receipt_digest","artifact_digest","audience","lifetime_seconds","approval_required","risk_classification","created_at"]); id(v.release_id,"$.release_id",e); if(v.preview_deployment_id!==undefined)id(v.preview_deployment_id,"$.preview_deployment_id",e); for(const k of ["source_bundle_digest","build_receipt_digest","artifact_digest"])digest(v[k],`$.${k}`,e); for(const k of ["created_at","expires_at"])if(v[k]!==undefined)time(v[k],`$.${k}`,e); if(!["self","team"].includes(v.audience))e.push(issue("$.audience","invalid_enum")); for(const k of ["lifetime_seconds","retention_seconds"])if(v[k]!==undefined&&(!Number.isSafeInteger(v[k])||v[k]<0||v[k]>31536000))e.push(issue(`$.${k}`,"invalid_limit")); str(v.risk_classification,"$.risk_classification",e,{max:32,pattern:/^(low|medium|high)$/ ,secret:false}); if(typeof v.approval_required!=="boolean")e.push(issue("$.approval_required","boolean_required")); return finish(v,e,"$"); }
export function normalizeApplicationGrant(input) { const [v,e]=base(input,schemas.applicationGrant,["version","kind","grant_id","organization_id","app_id","release_id","actor_id","session_id","operations","issued_at","expires_at","signing_purpose","key_id","request_digest"],["version","kind","grant_id","organization_id","app_id","actor_id","session_id","operations","issued_at","expires_at","signing_purpose","key_id","request_digest"]); for(const k of ["grant_id","organization_id","app_id","actor_id","session_id"])id(v[k],`$.${k}`,e); if(v.release_id!==undefined)id(v.release_id,"$.release_id",e); for(const k of ["issued_at","expires_at"])time(v[k],`$.${k}`,e); digest(v.request_digest,"$.request_digest",e); str(v.signing_purpose,"$.signing_purpose",e,{max:64,pattern:/^small-software\.application-grant$/ ,secret:false}); str(v.key_id,"$.key_id",e,{max:128,secret:false}); arr(v.operations,"$.operations",e,(x,p,a)=>str(x,p,a,{max:64,pattern:/^app\.(preview\.prepare|release\.request)$/ ,secret:false})); return finish(v,e,"$"); }
export function normalizeDeploymentReceipt(input) { const [v,e]=common(input,schemas.deploymentReceipt,["version","kind","organization_id","app_id","release_id","publish_plan_digest","artifact_digest","runtime_provider","provider_deployment_id","provider_version_id","route","active_generation","binding_ids","orchestrator_id","started_at","finished_at","state","reconciliation_digest"],["version","kind","organization_id","app_id","release_id","publish_plan_digest","artifact_digest","runtime_provider","provider_deployment_id","active_generation","orchestrator_id","started_at","finished_at","state"]); id(v.release_id,"$.release_id",e); for(const k of ["publish_plan_digest","artifact_digest","reconciliation_digest"])if(v[k]!==undefined)digest(v[k],`$.${k}`,e); id(v.orchestrator_id,"$.orchestrator_id",e); for(const k of ["started_at","finished_at"])time(v[k],`$.${k}`,e); str(v.runtime_provider,"$.runtime_provider",e,{max:64,pattern:/^[a-z][a-z0-9-]+$/,secret:false}); str(v.provider_deployment_id,"$.provider_deployment_id",e,{max:256,secret:false}); if(!Number.isSafeInteger(v.active_generation)||v.active_generation<1)e.push(issue("$.active_generation","invalid_generation")); str(v.state,"$.state",e,{max:32,pattern:/^(active|failed|reconciliation_required)$/ ,secret:false}); return finish(v,e,"$"); }
export function normalizeProviderOperation(input) { const [v,e]=base(input,schemas.providerOperation,["version","kind","operation_id","organization_id","app_id","release_id","provider","operation","request_digest","idempotency_key","state","created_at","expires_at"],["version","kind","operation_id","organization_id","app_id","provider","operation","request_digest","idempotency_key","state","created_at"]); for(const k of ["operation_id","organization_id","app_id"])id(v[k],`$.${k}`,e); if(v.release_id!==undefined)id(v.release_id,"$.release_id",e); digest(v.request_digest,"$.request_digest",e); str(v.idempotency_key,"$.idempotency_key",e,{max:256,pattern:/^[A-Za-z0-9][A-Za-z0-9._:-]{7,255}$/,secret:false}); str(v.provider,"$.provider",e,{max:64,secret:false}); str(v.operation,"$.operation",e,{max:64,secret:false}); str(v.state,"$.state",e,{max:32,pattern:/^(pending|accepted|uncertain|failed|reconciled)$/ ,secret:false}); time(v.created_at,"$.created_at",e); if(v.expires_at!==undefined)time(v.expires_at,"$.expires_at",e); return finish(v,e,"$"); }
export function normalizeProviderResult(input) { const [v,e]=base(input,schemas.providerResult,["version","kind","operation_id","provider","provider_result_digest","provider_resource_id","state","observed_at","redacted_metadata"],["version","kind","operation_id","provider","provider_result_digest","state","observed_at"]); id(v.operation_id,"$.operation_id",e); digest(v.provider_result_digest,"$.provider_result_digest",e); str(v.provider,"$.provider",e,{max:64,secret:false}); str(v.state,"$.state",e,{max:32,pattern:/^(succeeded|failed|unknown)$/ ,secret:false}); time(v.observed_at,"$.observed_at",e); if(v.provider_resource_id!==undefined)str(v.provider_resource_id,"$.provider_resource_id",e,{max:256,secret:false}); if(v.redacted_metadata!==undefined){object(v.redacted_metadata,"$.redacted_metadata"); for(const k of Object.keys(v.redacted_metadata))if(SECRET.test(k))e.push(issue(`$.redacted_metadata.${k}`,"secret_like_field"));} return finish(v,e,"$"); }

export const CONTRACTS = Object.freeze({ ...schemas });
export const normalizers = Object.freeze({ appManifest: normalizeAppManifest, sourceBundleStatement: normalizeSourceBundleStatement, buildReceipt: normalizeBuildReceipt, publishPlan: normalizePublishPlan, applicationGrant: normalizeApplicationGrant, deploymentReceipt: normalizeDeploymentReceipt, providerOperation: normalizeProviderOperation, providerResult: normalizeProviderResult });
export function canonicalJson(value) { return JSON.stringify(value, (_, v) => v && typeof v === "object" && !Array.isArray(v) ? Object.fromEntries(Object.keys(v).sort().map((k) => [k, v[k]])) : v); }
export function canonicalDigest(value) { return crypto.createHash("sha256").update(canonicalJson(value)).digest("hex"); }
export function redact(value) { if (Array.isArray(value)) return value.map(redact); if (!value || typeof value !== "object") return value; return Object.fromEntries(Object.entries(value).filter(([k]) => !SECRET.test(k)).map(([k,v])=>[k,redact(v)])); }
export function parseStrictJson(text) {
  if (typeof text !== "string" || Buffer.byteLength(text) > MAX.document) throw new SmallSoftwareContractError([issue("$", "document_too_large")]);
  const scopes = [], duplicates = [];
  let inString = false, escaped = false;
  for (let i = 0; i < text.length; i += 1) {
    const ch = text[i];
    if (inString) { if (escaped) escaped = false; else if (ch === "\\") escaped = true; else if (ch === '"') inString = false; continue; }
    if (ch === '"') {
      let j = i + 1, key = "", keyEscaped = false;
      for (; j < text.length; j += 1) { const next = text[j]; if (keyEscaped) { key += next; keyEscaped = false; } else if (next === "\\") keyEscaped = true; else if (next === '"') break; else key += next; }
      let k = j + 1; while (/\s/.test(text[k] ?? "")) k += 1;
      if (text[k] === ":" && scopes.length) { const scope = scopes.at(-1); if (scope.has(key)) duplicates.push(issue(`$.${key}`, "duplicate_field")); scope.add(key); }
      i = j; continue;
    }
    if (ch === "{") scopes.push(new Set());
    else if (ch === "}") scopes.pop();
  }
  if (duplicates.length) throw new SmallSoftwareContractError(duplicates);
  try { return JSON.parse(text); } catch { throw new SmallSoftwareContractError([issue("$", "invalid_json")]); }
}
