import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { performUninstallReinstallRecovery } from './uninstall-reinstall-recovery';
const success = (s = '') => ({ ok: true, exitCode: 0, stdout: Buffer.from(s), stderr: Buffer.alloc(0) }); const fail = () => ({ ok: false, exitCode: 1, stdout: Buffer.alloc(0), stderr: Buffer.from('not found') }); const env = (v) => success(`${JSON.stringify({ error: null, ok: true, public_key: v?.key ?? null, stdout_base64: v?.value === undefined ? null : Buffer.from(JSON.stringify(v.value)).toString('base64'), version: v?.version ?? null })}\n`);
const fixture = () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'p0c-uninstall-')); const app = path.join(root, 'Applications', 'AgentPass.app'); const home = path.join(root, 'home'); const state = path.join(root, 'system-state'); const plist = path.join(root, 'daemon.plist'); const broker = path.join(root, 'broker.plist'); const pkg = path.join(root, 'AgentPass.pkg'); fs.mkdirSync(app, { recursive: true }); fs.mkdirSync(path.join(home, '.agentpass'), { recursive: true, mode: 0o700 }); fs.mkdirSync(state, { recursive: true, mode: 0o700 }); fs.writeFileSync(path.join(home, '.agentpass', 'key'), 'keep'); fs.writeFileSync(path.join(state, 'audit'), 'keep'); fs.writeFileSync(plist, 'daemon'); fs.writeFileSync(broker, 'broker'); fs.writeFileSync(pkg, 'pkg'); return { root, app, home, state, plist, broker, pkg }; };
const release = (pkg) => ({ artifactPath: pkg, artifactSha256: crypto.createHash('sha256').update(fs.readFileSync(pkg)).digest('hex'), sourceCommit: 'b'.repeat(40), teamId: 'ABCDE12345' }); const noCheckpoint = async (_p, op) => op();
const machine = (v) => ({ applicationPath: v.app, checkpointDirectory: path.join(v.root, 'checkpoint'), testRepository: path.join(v.root, 'repo'), executables: { native_client: { path: '/client', sha256: 'c'.repeat(64) } } });
function harness(v) { let installed = true; const runCommand = async (command, args) => { if (command === '/bin/launchctl' || command === '/usr/sbin/pkgutil' && args[0] === '--pkg-info') return installed ? success('present') : fail(); if (command === '/usr/local/bin/agentpass' && args.includes('--execute')) { if (args.includes('--system')) { installed = false; fs.rmSync(v.app, { recursive: true, force: true }); fs.rmSync(v.plist, { force: true }); } else fs.rmSync(v.broker, { force: true }); return success('{}'); } if (command === '/usr/sbin/installer') { installed = true; fs.mkdirSync(v.app, { recursive: true }); fs.writeFileSync(v.plist, 'daemon'); } return success(); }; const runPinned = async (_e, args) => args.at(-1) === 'public-key' ? env({ key: 'ssh-ed25519 AAAAdevice' }) : args.at(-1) === 'audit-public-key' ? env({ key: 'ssh-ed25519 AAAAaudit' }) : args.at(-1) === 'key-lifecycle-status' ? env({ value: { generation: 1 } }) : env({ version: 13 }); return { runCommand, runPinned }; }
test('uninstall/reinstall removes the install boundary and recovers retained identity', async () => { const v = fixture(); try { const h = harness(v); assert.deepEqual(await performUninstallReinstallRecovery({ release: release(v.pkg), machine: machine(v), production: false, getUid: () => 0, homeDirectory: v.home, systemStatePath: v.state, nativePlistPath: v.plist, brokerPlistPath: v.broker, runCommand: h.runCommand, runPinned: h.runPinned, withCheckpoint: noCheckpoint }), ['uninstall-reinstall-recovery']); assert.equal(fs.existsSync(v.state), true); } finally { fs.rmSync(v.root, { recursive: true, force: true }); } });
test('uninstall/reinstall rejects an altered package and symlinked retained state', async () => { const v = fixture(); try { const r = release(v.pkg); fs.appendFileSync(v.pkg, 'tamper'); await assert.rejects(() => performUninstallReinstallRecovery({ release: r, machine: machine(v), production: false, getUid: () => 0, withCheckpoint: noCheckpoint }), /digest mismatch/u); } finally { fs.rmSync(v.root, { recursive: true, force: true }); } const w = fixture(); try { fs.rmSync(path.join(w.home, '.agentpass'), { recursive: true }); fs.symlinkSync(w.root, path.join(w.home, '.agentpass')); const h = harness(w); await assert.rejects(() => performUninstallReinstallRecovery({ release: release(w.pkg), machine: machine(w), production: false, getUid: () => 0, homeDirectory: w.home, systemStatePath: w.state, nativePlistPath: w.plist, brokerPlistPath: w.broker, runCommand: h.runCommand, runPinned: h.runPinned, withCheckpoint: noCheckpoint }), /unsafe/u); } finally { fs.rmSync(w.root, { recursive: true, force: true }); } });
