import CryptoKit
import Foundation

/// Fail-closed errors for the authenticated Git bridge.  The cases are
/// deliberately non-parametric so no peer supplied value can leak through a
/// service error or an audit record.
public enum NativeAgentAuthenticatedGitBridgeError: String, Error, Equatable, Sendable, LocalizedError {
    case invalidRequest = "invalid_request"
    case invalidSessionState = "invalid_session_state"
    case peerIdentityMismatch = "peer_identity_mismatch"
    case processIdentityChanged = "process_identity_changed"
    case codeIdentityDenied = "code_identity_denied"
    case requestAuthenticationFailed = "request_authentication_failed"
    case requestReplay = "request_replay"
    case requestSequenceMismatch = "request_sequence_mismatch"
    case sessionClosed = "session_closed"

    public var errorDescription: String? { rawValue }
}

/// The immutable peer binding captured when an authenticated connection is
/// accepted.  It combines the complete connection projection (including the
/// one-way audit-token identity) with the independently observed process code
/// identity and ancestry.
///
/// A caller must provide a fresh `NativeConnectionContext` and a fresh OS
/// observation before every protected key use.  Neither request DTOs nor
/// argv/environment values participate in this binding.
public struct NativeAgentAuthenticatedGitBridgePeerBinding: Sendable {
    public let connectionContext: NativeConnectionContext
    public let processIdentity: NativeProcessIdentity
    public let processBindingHash: String
    public let ancestryBindingHash: String

    private let connectionGuard: NativeAgentConnectionGuard
    private let processPolicy: NativeProcessIdentityPolicy

    public init(
        connectionContext: NativeConnectionContext,
        observation: NativeProcessObservation,
        processPolicy: NativeProcessIdentityPolicy
    ) throws {
        let connectionGuard: NativeAgentConnectionGuard
        do {
            connectionGuard = try NativeAgentConnectionGuard(
                context: connectionContext,
                observation: observation
            )
        } catch NativeAgentConnectionGuardError.connectionObservationMismatch {
            throw NativeAgentAuthenticatedGitBridgeError.peerIdentityMismatch
        } catch {
            throw NativeAgentAuthenticatedGitBridgeError.processIdentityChanged
        }

        let identity = connectionGuard.initialIdentity
        guard identity.matches(policy: processPolicy) else {
            throw NativeAgentAuthenticatedGitBridgeError.codeIdentityDenied
        }

        self.connectionContext = connectionContext
        self.processIdentity = identity
        self.processBindingHash = connectionGuard.processBindingHash
        self.ancestryBindingHash = connectionGuard.ancestryBindingHash
        self.connectionGuard = connectionGuard
        self.processPolicy = processPolicy
    }

    /// Revalidates the live XPC peer and its full process identity.
    ///
    /// Equality of the contexts is intentional: it compares the PID,
    /// PID-generation, audit-session and complete audit-token identity digest.
    /// UID-only checks are therefore insufficient to pass this boundary.
    public func revalidate(
        connectionContext reobservedContext: NativeConnectionContext,
        observation: NativeProcessObservation
    ) throws {
        guard reobservedContext == connectionContext else {
            throw NativeAgentAuthenticatedGitBridgeError.peerIdentityMismatch
        }
        do {
            try connectionGuard.revalidate(observation: observation)
        } catch NativeAgentConnectionGuardError.connectionObservationMismatch {
            throw NativeAgentAuthenticatedGitBridgeError.peerIdentityMismatch
        } catch {
            throw NativeAgentAuthenticatedGitBridgeError.processIdentityChanged
        }

        guard NativeProcessIdentity(observation: observation).matches(policy: processPolicy) else {
            throw NativeAgentAuthenticatedGitBridgeError.codeIdentityDenied
        }
    }

    public var auditTokenIdentity: String { connectionContext.tokenIdentity }
    public var effectiveUserID: UInt32 { connectionContext.effectiveUserID }
}

/// The only bridge sign request.  It carries an opaque bounded payload and a
/// proof generated by an in-memory session authenticator.  No private key,
/// capability, path, repository, argv, environment, or file reference is
/// representable by this DTO.
@objc(NativeAgentAuthenticatedGitBridgeSignRequest)
public final class NativeAgentAuthenticatedGitBridgeSignRequest: NSObject, NSSecureCoding {
    public static var supportsSecureCoding: Bool { true }

    public let sessionID: String
    public let requestSequence: UInt32
    public let payload: Data
    public let payloadDigest: Data
    public let proof: Data

    internal init?(
        sessionID: String,
        requestSequence: UInt32,
        payload: Data,
        proof: Data
    ) {
        guard let sessionID = NativeAgentAuthenticatedGitBridgeContract.canonicalUUID(sessionID),
              (1...NativeAgentAuthenticatedGitBridgeContract.maximumRequests).contains(requestSequence),
              !payload.isEmpty,
              payload.count <= NativeAgentAuthenticatedGitBridgeContract.maximumPayloadBytes,
              proof.count == NativeAgentAuthenticatedGitBridgeContract.proofBytes else {
            return nil
        }
        self.sessionID = sessionID
        self.requestSequence = requestSequence
        self.payload = payload
        self.payloadDigest = Data(SHA256.hash(data: payload))
        self.proof = proof
        super.init()
    }

    public required convenience init?(coder: NSCoder) {
        guard !Self.containsForbiddenKey(coder),
              let sessionID = coder.decodeObject(of: NSString.self, forKey: Keys.sessionID) as String?,
              let requestSequence = coder.decodeObject(of: NSNumber.self, forKey: Keys.requestSequence)?.uint32Value,
              let payload = coder.decodeObject(of: NSData.self, forKey: Keys.payload) as Data?,
              let proof = coder.decodeObject(of: NSData.self, forKey: Keys.proof) as Data? else {
            return nil
        }
        self.init(sessionID: sessionID, requestSequence: requestSequence, payload: payload, proof: proof)
    }

    public func encode(with coder: NSCoder) {
        coder.encode(sessionID as NSString, forKey: Keys.sessionID)
        coder.encode(NSNumber(value: requestSequence), forKey: Keys.requestSequence)
        coder.encode(payload as NSData, forKey: Keys.payload)
        coder.encode(proof as NSData, forKey: Keys.proof)
    }

    private enum Keys {
        static let sessionID = "session_id"
        static let requestSequence = "request_sequence"
        static let payload = "payload"
        static let proof = "proof"
    }

    private static let forbiddenKeys = [
        "capability", "capability_id", "private_key", "private_key_data",
        "key", "key_id", "algorithm", "repository", "repository_path",
        "worktree_path", "session_token", "token", "ttl_seconds", "scope",
        "authority", "lease", "argv", "environment", "env", "file", "path"
    ]

    private static func containsForbiddenKey(_ coder: NSCoder) -> Bool {
        forbiddenKeys.contains { coder.containsValue(forKey: $0) }
    }
}

/// A small in-memory MAC primitive for request proof and replay resistance.
/// The key is never encoded, returned, written to disk, or placed in a
/// process argument/environment.  XPC peer authentication still comes from
/// the peer binding; this MAC binds the request to the connection-scoped
/// identity and to the session/sequence/payload tuple.
public struct NativeAgentAuthenticatedGitBridgeRequestAuthenticator: Sendable {
    private let key: SymmetricKey

    public init() {
        self.key = SymmetricKey(size: .bits256)
    }

    internal init?(keyData: Data) {
        guard keyData.count == 32 else { return nil }
        self.key = SymmetricKey(data: keyData)
    }

    public func makeRequest(
        sessionID: String,
        requestSequence: UInt32,
        payload: Data,
        peer: NativeAgentAuthenticatedGitBridgePeerBinding
    ) -> NativeAgentAuthenticatedGitBridgeSignRequest? {
        guard let canonicalSessionID = NativeAgentAuthenticatedGitBridgeContract.canonicalUUID(sessionID),
              let request = NativeAgentAuthenticatedGitBridgeSignRequest(
                sessionID: canonicalSessionID,
                requestSequence: requestSequence,
                payload: payload,
                proof: Data(repeating: 0, count: NativeAgentAuthenticatedGitBridgeContract.proofBytes)
              ) else {
            return nil
        }

        let proof = proof(for: request, peer: peer)
        return NativeAgentAuthenticatedGitBridgeSignRequest(
            sessionID: request.sessionID,
            requestSequence: request.requestSequence,
            payload: request.payload,
            proof: proof
        )
    }

    internal func verify(
        request: NativeAgentAuthenticatedGitBridgeSignRequest,
        expectedSessionID: String,
        peer: NativeAgentAuthenticatedGitBridgePeerBinding
    ) -> Bool {
        guard request.sessionID == expectedSessionID.lowercased() else { return false }
        let expected = proof(for: request, peer: peer)
        return expected.withUnsafeBytes { expectedBytes in
            request.proof.withUnsafeBytes { actualBytes in
                guard expectedBytes.count == actualBytes.count else { return false }
                var difference: UInt8 = 0
                for index in 0..<expectedBytes.count {
                    difference |= expectedBytes[index] ^ actualBytes[index]
                }
                return difference == 0
            }
        }
    }

    private func proof(
        for request: NativeAgentAuthenticatedGitBridgeSignRequest,
        peer: NativeAgentAuthenticatedGitBridgePeerBinding
    ) -> Data {
        let data = NativeAgentAuthenticatedGitBridgeContract.authenticationData(
            sessionID: request.sessionID,
            requestSequence: request.requestSequence,
            payloadDigest: request.payloadDigest,
            peer: peer
        )
        return Data(HMAC<SHA256>.authenticationCode(for: data, using: key))
    }
}

/// A connection-owned, fail-closed session state machine.  It validates the
/// peer immediately before consuming every sign request.  It returns only an
/// authorized opaque payload to the future signer; it never handles a private
/// key or a secret transport mechanism.
public final class NativeAgentAuthenticatedGitBridgeSession: @unchecked Sendable {
    public enum Phase: String, CaseIterable, Sendable {
        case new
        case prepared
        case attached
        case closed
    }

    public struct Snapshot: Equatable, Sendable {
        public let sessionID: String
        public let phase: Phase
        public let requestCount: Int
        public let launchNonceDigest: Data?

        fileprivate init(sessionID: String, phase: Phase, requestCount: Int, launchNonceDigest: Data?) {
            self.sessionID = sessionID
            self.phase = phase
            self.requestCount = requestCount
            self.launchNonceDigest = launchNonceDigest
        }
    }

    public struct AuthorizedPayload: Equatable, Sendable {
        public let sessionID: String
        public let requestSequence: UInt32
        public let payload: Data
        public let payloadDigest: Data
        public let peerProcessBindingHash: String
        public let peerAuditTokenIdentity: String

        fileprivate init(
            sessionID: String,
            requestSequence: UInt32,
            payload: Data,
            payloadDigest: Data,
            peerProcessBindingHash: String,
            peerAuditTokenIdentity: String
        ) {
            self.sessionID = sessionID
            self.requestSequence = requestSequence
            self.payload = payload
            self.payloadDigest = payloadDigest
            self.peerProcessBindingHash = peerProcessBindingHash
            self.peerAuditTokenIdentity = peerAuditTokenIdentity
        }
    }

    public let sessionID: String
    public let peer: NativeAgentAuthenticatedGitBridgePeerBinding

    private let authenticator: NativeAgentAuthenticatedGitBridgeRequestAuthenticator
    private let childPolicy: NativeProcessIdentityPolicy
    private let stateLock = NSLock()
    private var phase: Phase = .new
    private var launchNonceDigest: Data?
    private var consumedSequences: Set<UInt32> = []

    public init(
        sessionID: String,
        peer: NativeAgentAuthenticatedGitBridgePeerBinding,
        childPolicy: NativeProcessIdentityPolicy,
        authenticator: NativeAgentAuthenticatedGitBridgeRequestAuthenticator = .init()
    ) throws {
        guard let sessionID = NativeAgentAuthenticatedGitBridgeContract.canonicalUUID(sessionID) else {
            throw NativeAgentAuthenticatedGitBridgeError.invalidRequest
        }
        self.sessionID = sessionID
        self.peer = peer
        self.childPolicy = childPolicy
        self.authenticator = authenticator
    }

    public var snapshot: Snapshot {
        stateLock.lock()
        defer { stateLock.unlock() }
        return snapshotUnlocked()
    }

    private func snapshotUnlocked() -> Snapshot {
        Snapshot(
            sessionID: sessionID,
            phase: phase,
            requestCount: consumedSequences.count,
            launchNonceDigest: launchNonceDigest
        )
    }

    public func prepare(launchNonce: Data) throws -> Snapshot {
        stateLock.lock()
        defer { stateLock.unlock() }
        guard phase == .new,
              (NativeAgentAuthenticatedGitBridgeContract.minimumNonceBytes...NativeAgentAuthenticatedGitBridgeContract.maximumNonceBytes).contains(launchNonce.count) else {
            throw phase == .closed ? NativeAgentAuthenticatedGitBridgeError.sessionClosed : NativeAgentAuthenticatedGitBridgeError.invalidSessionState
        }
        launchNonceDigest = Data(SHA256.hash(data: launchNonce))
        phase = .prepared
        return snapshotUnlocked()
    }

    public func attach(childIdentity: NativeProcessIdentity) throws -> Snapshot {
        stateLock.lock()
        defer { stateLock.unlock() }
        guard phase == .prepared else {
            throw phase == .closed ? NativeAgentAuthenticatedGitBridgeError.sessionClosed : NativeAgentAuthenticatedGitBridgeError.invalidSessionState
        }
        guard childIdentity.matches(policy: childPolicy) else {
            phase = .closed
            throw NativeAgentAuthenticatedGitBridgeError.codeIdentityDenied
        }
        phase = .attached
        return snapshotUnlocked()
    }

    public func makeRequest(
        requestSequence: UInt32,
        payload: Data
    ) -> NativeAgentAuthenticatedGitBridgeSignRequest? {
        stateLock.lock()
        defer { stateLock.unlock() }
        guard phase == .attached,
              !consumedSequences.contains(requestSequence) else { return nil }
        return authenticator.makeRequest(
            sessionID: sessionID,
            requestSequence: requestSequence,
            payload: payload,
            peer: peer
        )
    }

    public func authorizeAndConsume(
        _ request: NativeAgentAuthenticatedGitBridgeSignRequest,
        reobservedConnectionContext: NativeConnectionContext,
        reobservedObservation: NativeProcessObservation
    ) throws -> AuthorizedPayload {
        stateLock.lock()
        defer { stateLock.unlock() }
        guard phase == .attached else {
            throw phase == .closed ? NativeAgentAuthenticatedGitBridgeError.sessionClosed : NativeAgentAuthenticatedGitBridgeError.invalidSessionState
        }
        guard request.sessionID == sessionID else {
            phase = .closed
            throw NativeAgentAuthenticatedGitBridgeError.requestAuthenticationFailed
        }
        guard !consumedSequences.contains(request.requestSequence) else {
            phase = .closed
            throw NativeAgentAuthenticatedGitBridgeError.requestReplay
        }
        guard request.requestSequence == UInt32(consumedSequences.count + 1) else {
            phase = .closed
            throw NativeAgentAuthenticatedGitBridgeError.requestSequenceMismatch
        }

        do {
            try peer.revalidate(
                connectionContext: reobservedConnectionContext,
                observation: reobservedObservation
            )
        } catch NativeAgentAuthenticatedGitBridgeError.peerIdentityMismatch {
            phase = .closed
            throw NativeAgentAuthenticatedGitBridgeError.peerIdentityMismatch
        } catch NativeAgentAuthenticatedGitBridgeError.codeIdentityDenied {
            phase = .closed
            throw NativeAgentAuthenticatedGitBridgeError.codeIdentityDenied
        } catch {
            phase = .closed
            throw NativeAgentAuthenticatedGitBridgeError.processIdentityChanged
        }

        guard authenticator.verify(request: request, expectedSessionID: sessionID, peer: peer) else {
            phase = .closed
            throw NativeAgentAuthenticatedGitBridgeError.requestAuthenticationFailed
        }

        consumedSequences.insert(request.requestSequence)
        return AuthorizedPayload(
            sessionID: sessionID,
            requestSequence: request.requestSequence,
            payload: request.payload,
            payloadDigest: request.payloadDigest,
            peerProcessBindingHash: peer.processBindingHash,
            peerAuditTokenIdentity: peer.auditTokenIdentity
        )
    }

    public func close() -> Snapshot {
        stateLock.lock()
        defer { stateLock.unlock() }
        phase = .closed
        return snapshotUnlocked()
    }
}

public enum NativeAgentAuthenticatedGitBridgeContract {
    public static let protocolVersion = 1
    public static let minimumNonceBytes = 16
    public static let maximumNonceBytes = 64
    public static let maximumPayloadBytes = 1 * 1024 * 1024
    public static let maximumRequests: UInt32 = 2
    public static let proofBytes = 32

    fileprivate static func canonicalUUID(_ value: String) -> String? {
        guard value.utf8.count == 36, let uuid = UUID(uuidString: value) else { return nil }
        return uuid.uuidString.lowercased()
    }

    fileprivate static func authenticationData(
        sessionID: String,
        requestSequence: UInt32,
        payloadDigest: Data,
        peer: NativeAgentAuthenticatedGitBridgePeerBinding
    ) -> Data {
        var data = Data("AgentPass-Authenticated-Git-Bridge-v1\0".utf8)
        appendLengthPrefixed(Data(sessionID.utf8), to: &data)
        var sequence = requestSequence.bigEndian
        withUnsafeBytes(of: &sequence) { data.append(contentsOf: $0) }
        appendLengthPrefixed(payloadDigest, to: &data)
        appendLengthPrefixed(Data(peer.auditTokenIdentity.utf8), to: &data)
        appendLengthPrefixed(Data(peer.processBindingHash.utf8), to: &data)
        appendLengthPrefixed(Data(peer.ancestryBindingHash.utf8), to: &data)
        return data
    }

    private static func appendLengthPrefixed(_ value: Data, to data: inout Data) {
        var length = UInt32(value.count).bigEndian
        withUnsafeBytes(of: &length) { data.append(contentsOf: $0) }
        data.append(value)
    }
}
