import Foundation

/// Stable, secret-free failures for the service-owned Host signing route.
public enum NativeAgentHostSigningRouteError: String, Error, Equatable, Sendable {
    case invalidInput = "invalid_input"
    case routeMissing = "route_missing"
    case routeReplay = "route_replay"
    case connectionMismatch = "connection_mismatch"
    case childProcessMismatch = "child_process_mismatch"
    case worktreeMismatch = "worktree_mismatch"
    case requestCorrelationMismatch = "request_correlation_mismatch"
    case expired = "expired"
    case closed = "closed"
    case invalidated = "invalidated"
    case transitionDenied = "transition_denied"
}

/// The only correlation values that a Host may echo for a one-shot signing
/// route. Both values are generated by the service; this type has no public
/// initializer so a Host or Child cannot manufacture a valid correlation.
public struct NativeAgentHostSigningRequestCorrelation: Equatable, Hashable, Sendable {
    public let requestID: String
    public let createdAtMilliseconds: Int64

    internal init(serviceIssuedAtMilliseconds: Int64) throws {
        guard AgentPassHostXPCContract.isTimestamp(serviceIssuedAtMilliseconds) else {
            throw NativeAgentHostSigningRouteError.invalidInput
        }
        self.requestID = UUID().uuidString.lowercased()
        self.createdAtMilliseconds = serviceIssuedAtMilliseconds
    }

    internal init(requestID: String, createdAtMilliseconds: Int64) throws {
        guard AgentPassHostXPCContract.canonicalUUID(requestID) == requestID,
              AgentPassHostXPCContract.isTimestamp(createdAtMilliseconds) else {
            throw NativeAgentHostSigningRouteError.invalidInput
        }
        self.requestID = requestID
        self.createdAtMilliseconds = createdAtMilliseconds
    }
}

public enum NativeAgentHostSigningRouteState: String, Equatable, Sendable {
    case issued
    case consumed
    case executing
    case completed
    case expired
    case closed
    case invalidated
    case outcomeUnknown = "outcome_unknown"
}

/// A redacted status projection. The route's connection, child, and worktree
/// bindings are intentionally absent; the service uses them only for exact
/// comparison during consumption.
public struct NativeAgentHostSigningRouteStatus: Equatable, Sendable {
    public let routeID: String
    public let state: NativeAgentHostSigningRouteState
    public let expiresAtMilliseconds: Int64
    public let requestCorrelation: NativeAgentHostSigningRequestCorrelation

    fileprivate init(route: NativeAgentHostSigningRoute) {
        self.routeID = route.routeID
        self.state = route.currentState
        self.expiresAtMilliseconds = route.expiresAtMilliseconds
        self.requestCorrelation = route.requestCorrelation
    }
}

/// One opaque, service-issued opportunity to delegate a Host signing request.
///
/// The adapter is retained privately. No lease, capability, transaction
/// authority, key selector, or signer configuration is part of this route's
/// public surface. Its private bindings are compared only by the registry's
/// atomic consume path. A route is unusable until the registry consumes it and
/// can execute at most once after that claim.
public final class NativeAgentHostSigningRoute: @unchecked Sendable {
    public let routeID: String
    public let expiresAtMilliseconds: Int64
    public let requestCorrelation: NativeAgentHostSigningRequestCorrelation

    private let adapter: NativeAgentSessionCoordinatorSigningAdapter
    private let connectionTokenIdentity: String
    private let childProcessBindingHash: String
    private let worktreeBindingDigest: Data
    private let lock = NSLock()
    private var state: NativeAgentHostSigningRouteState = .issued

    fileprivate init(
        routeID: String,
        adapter: NativeAgentSessionCoordinatorSigningAdapter,
        connectionTokenIdentity: String,
        childProcessIdentity: NativeProcessIdentity,
        worktreeBindingDigest: Data,
        expiresAtMilliseconds: Int64,
        requestCorrelation: NativeAgentHostSigningRequestCorrelation
    ) throws {
        guard Self.isRouteID(routeID),
              Self.isHash(connectionTokenIdentity),
              Self.isDigest(worktreeBindingDigest),
              AgentPassHostXPCContract.isTimestamp(expiresAtMilliseconds) else {
            throw NativeAgentHostSigningRouteError.invalidInput
        }
        self.routeID = routeID
        self.adapter = adapter
        self.connectionTokenIdentity = connectionTokenIdentity
        self.childProcessBindingHash = childProcessIdentity.canonicalBindingHash
        self.worktreeBindingDigest = worktreeBindingDigest
        self.expiresAtMilliseconds = expiresAtMilliseconds
        self.requestCorrelation = requestCorrelation
    }

    public var currentState: NativeAgentHostSigningRouteState {
        lock.withLock { state }
    }

    /// Claims the route exactly once after all independently observed bindings
    /// and the service-issued correlation pair have matched.
    fileprivate func consume(
        connectionTokenIdentity: String,
        childProcessIdentity: NativeProcessIdentity,
        worktreeBindingDigest: Data,
        requestCorrelation: NativeAgentHostSigningRequestCorrelation,
        nowMilliseconds: Int64
    ) throws {
        try lock.withLock {
            try validateBindings(
                connectionTokenIdentity: connectionTokenIdentity,
                childProcessIdentity: childProcessIdentity,
                worktreeBindingDigest: worktreeBindingDigest,
                requestCorrelation: requestCorrelation
            )
            switch state {
            case .issued:
                guard AgentPassHostXPCContract.isTimestamp(nowMilliseconds) else {
                    throw NativeAgentHostSigningRouteError.invalidInput
                }
                guard nowMilliseconds < expiresAtMilliseconds else {
                    state = .expired
                    throw NativeAgentHostSigningRouteError.expired
                }
                state = .consumed
            case .consumed, .executing, .completed, .outcomeUnknown:
                throw NativeAgentHostSigningRouteError.routeReplay
            case .expired:
                throw NativeAgentHostSigningRouteError.expired
            case .closed:
                throw NativeAgentHostSigningRouteError.closed
            case .invalidated:
                throw NativeAgentHostSigningRouteError.invalidated
            }
        }
    }

    /// Delegates the already-claimed request to the existing Core signing
    /// adapter. The adapter's authority-bearing transaction record is consumed
    /// internally; callers receive only the provider's signature bytes.
    public func execute(
        provider: @escaping @Sendable (Data) throws -> Data
    ) throws -> Data {
        try lock.withLock {
            guard state == .consumed else {
                switch state {
                case .closed: throw NativeAgentHostSigningRouteError.closed
                case .invalidated: throw NativeAgentHostSigningRouteError.invalidated
                case .expired: throw NativeAgentHostSigningRouteError.expired
                case .consumed: throw NativeAgentHostSigningRouteError.transitionDenied
                case .issued: throw NativeAgentHostSigningRouteError.transitionDenied
                case .executing, .completed, .outcomeUnknown:
                    throw NativeAgentHostSigningRouteError.routeReplay
                }
            }
            state = .executing
            do {
                let record = try adapter.execute(provider: provider)
                guard let signature = record.signature else {
                    state = .outcomeUnknown
                    throw NativeAgentHostSigningRouteError.transitionDenied
                }
                let signatureData = Data(signature.utf8)
                guard !signatureData.isEmpty else {
                    state = .outcomeUnknown
                    throw NativeAgentHostSigningRouteError.transitionDenied
                }
                state = .completed
                return signatureData
            } catch {
                state = .outcomeUnknown
                throw error
            }
        }
    }

    fileprivate func close(connectionTokenIdentity: String) throws {
        try lock.withLock {
            guard self.connectionTokenIdentity == connectionTokenIdentity else {
                throw NativeAgentHostSigningRouteError.connectionMismatch
            }
            switch state {
            case .issued, .consumed, .completed:
                state = .closed
            case .closed:
                break
            case .invalidated:
                throw NativeAgentHostSigningRouteError.invalidated
            case .expired:
                throw NativeAgentHostSigningRouteError.expired
            case .outcomeUnknown:
                throw NativeAgentHostSigningRouteError.routeReplay
            case .executing:
                throw NativeAgentHostSigningRouteError.transitionDenied
            }
        }
    }

    fileprivate func invalidate() {
        lock.withLock {
            switch state {
            case .issued, .consumed, .completed:
                state = .invalidated
            case .executing, .expired, .closed, .invalidated, .outcomeUnknown:
                break
            }
        }
    }

    fileprivate func status() -> NativeAgentHostSigningRouteStatus {
        NativeAgentHostSigningRouteStatus(route: self)
    }

    private func validateBindings(
        connectionTokenIdentity: String,
        childProcessIdentity: NativeProcessIdentity,
        worktreeBindingDigest: Data,
        requestCorrelation: NativeAgentHostSigningRequestCorrelation
    ) throws {
        guard self.connectionTokenIdentity == connectionTokenIdentity else {
            throw NativeAgentHostSigningRouteError.connectionMismatch
        }
        guard childProcessBindingHash == childProcessIdentity.canonicalBindingHash else {
            throw NativeAgentHostSigningRouteError.childProcessMismatch
        }
        guard worktreeBindingDigest == self.worktreeBindingDigest else {
            throw NativeAgentHostSigningRouteError.worktreeMismatch
        }
        guard requestCorrelation == self.requestCorrelation else {
            throw NativeAgentHostSigningRouteError.requestCorrelationMismatch
        }
    }

    private static func isRouteID(_ value: String) -> Bool {
        AgentPassHostXPCContract.canonicalUUID(value) == value
    }

    private static func isHash(_ value: String) -> Bool {
        value.count == 64 && value.range(of: "^[0-9a-f]{64}$", options: .regularExpression) != nil
    }

    private static func isDigest(_ value: Data) -> Bool {
        value.count == NativeAgentSessionBinding.digestByteCount
            && value.contains(where: { $0 != 0 })
    }
}

/// Service-wide in-memory registry for opaque Host signing routes.
///
/// Route issuance deliberately has no route-ID parameter. The service creates
/// the route ID and correlation pair inside this registry, while all later
/// operations are serialized under one lock and retain terminal tombstones for
/// replay/close/invalidation decisions. The registry is not Codable: routes do
/// not survive a service restart.
public final class NativeAgentHostSigningRouteRegistry: @unchecked Sendable {
    private let lock = NSLock()
    private var routes: [String: NativeAgentHostSigningRoute] = [:]

    public init() {}

    /// Issues a route from a service-created signing adapter and independent
    /// Host/Child observations. No caller can select the route ID or request
    /// correlation values.
    public func issue(
        adapter: NativeAgentSessionCoordinatorSigningAdapter,
        connectionTokenIdentity: String,
        childProcessIdentity: NativeProcessIdentity,
        worktreeBindingDigest: Data,
        expiresAtMilliseconds: Int64,
        nowMilliseconds: Int64
    ) throws -> NativeAgentHostSigningRoute {
        guard Self.isHash(connectionTokenIdentity),
              Self.isDigest(worktreeBindingDigest),
              AgentPassHostXPCContract.isTimestamp(nowMilliseconds),
              AgentPassHostXPCContract.isTimestamp(expiresAtMilliseconds),
              nowMilliseconds < expiresAtMilliseconds else {
            throw NativeAgentHostSigningRouteError.invalidInput
        }

        return try lock.withLock {
            var routeID = UUID().uuidString.lowercased()
            while routes[routeID] != nil {
                routeID = UUID().uuidString.lowercased()
            }
            let correlation = try NativeAgentHostSigningRequestCorrelation(
                serviceIssuedAtMilliseconds: nowMilliseconds)
            let route = try NativeAgentHostSigningRoute(
                routeID: routeID,
                adapter: adapter,
                connectionTokenIdentity: connectionTokenIdentity,
                childProcessIdentity: childProcessIdentity,
                worktreeBindingDigest: worktreeBindingDigest,
                expiresAtMilliseconds: expiresAtMilliseconds,
                requestCorrelation: correlation
            )
            routes[routeID] = route
            return route
        }
    }

    public func status(routeID: String) throws -> NativeAgentHostSigningRouteStatus {
        try lock.withLock {
            try route(for: routeID).status()
        }
    }

    /// Atomically validates the exact Host/Child/worktree/correlation tuple
    /// and marks the route consumed before returning it for execution.
    @discardableResult
    public func consume(
        routeID: String,
        connectionTokenIdentity: String,
        childProcessIdentity: NativeProcessIdentity,
        worktreeBindingDigest: Data,
        requestCorrelation: NativeAgentHostSigningRequestCorrelation,
        nowMilliseconds: Int64
    ) throws -> NativeAgentHostSigningRoute {
        try lock.withLock {
            let route = try route(for: routeID)
            try route.consume(
                connectionTokenIdentity: connectionTokenIdentity,
                childProcessIdentity: childProcessIdentity,
                worktreeBindingDigest: worktreeBindingDigest,
                requestCorrelation: requestCorrelation,
                nowMilliseconds: nowMilliseconds
            )
            return route
        }
    }

    /// Convenience operation that performs the atomic consume and then
    /// delegates exactly one provider invocation through the retained adapter.
    public func execute(
        routeID: String,
        connectionTokenIdentity: String,
        childProcessIdentity: NativeProcessIdentity,
        worktreeBindingDigest: Data,
        requestCorrelation: NativeAgentHostSigningRequestCorrelation,
        nowMilliseconds: Int64,
        provider: @escaping @Sendable (Data) throws -> Data
    ) throws -> Data {
        let route = try consume(
            routeID: routeID,
            connectionTokenIdentity: connectionTokenIdentity,
            childProcessIdentity: childProcessIdentity,
            worktreeBindingDigest: worktreeBindingDigest,
            requestCorrelation: requestCorrelation,
            nowMilliseconds: nowMilliseconds
        )
        return try route.execute(provider: provider)
    }

    public func close(routeID: String, connectionTokenIdentity: String) throws {
        try lock.withLock {
            try route(for: routeID).close(connectionTokenIdentity: connectionTokenIdentity)
        }
    }

    /// Invalidates one route without accepting any caller identity as a new
    /// authority. This is used by service lifecycle cleanup after connection
    /// loss, child exit, or process/worktree drift.
    public func invalidate(routeID: String) throws {
        try lock.withLock {
            try route(for: routeID).invalidate()
        }
    }

    @discardableResult
    public func invalidateAll() -> Int {
        lock.withLock {
            var invalidated = 0
            for route in routes.values {
                let before = route.currentState
                route.invalidate()
                if before != route.currentState, route.currentState == .invalidated {
                    invalidated += 1
                }
            }
            return invalidated
        }
    }

    private func route(for routeID: String) throws -> NativeAgentHostSigningRoute {
        guard Self.isRouteID(routeID) else {
            throw NativeAgentHostSigningRouteError.invalidInput
        }
        guard let route = routes[routeID] else {
            throw NativeAgentHostSigningRouteError.routeMissing
        }
        return route
    }

    private static func isRouteID(_ value: String) -> Bool {
        AgentPassHostXPCContract.canonicalUUID(value) == value
    }

    private static func isHash(_ value: String) -> Bool {
        value.count == 64 && value.range(of: "^[0-9a-f]{64}$", options: .regularExpression) != nil
    }

    private static func isDigest(_ value: Data) -> Bool {
        value.count == NativeAgentSessionBinding.digestByteCount
            && value.contains(where: { $0 != 0 })
    }
}
