import Foundation

@objc public protocol AgentPassNativeServiceProtocol {
    func health(withReply reply: @escaping (NSDictionary) -> Void)
    func publicKey(withReply reply: @escaping (NSString?, NSError?) -> Void)
    func sign(request: NSData, withReply reply: @escaping (NSString?, NSError?) -> Void)
    func auditStatus(withReply reply: @escaping (NSData?, NSError?) -> Void)
    func auditPublicKey(withReply reply: @escaping (NSString?, NSError?) -> Void)
    func createAuditCheckpoint(withReply reply: @escaping (NSData?, NSError?) -> Void)
    func rotateAudit(withReply reply: @escaping (NSData?, NSError?) -> Void)
    func rotateAuditEvidence(withReply reply: @escaping (NSData?, NSError?) -> Void)
    func keyLifecycleStatus(withReply reply: @escaping (NSData?, NSError?) -> Void)
    func stageKey(role: NSString, withReply reply: @escaping (NSData?, NSError?) -> Void)
    func approvalKeyStagePlan(withReply reply: @escaping (NSData?, NSError?) -> Void)
    func stageApprovalKey(generation: Int, applicationTag: NSString, publicKey: NSData, withReply reply: @escaping (NSData?, NSError?) -> Void)
    func beginKeyActivation(role: NSString, generation: Int, reason: NSString, withReply reply: @escaping (NSData?, NSError?) -> Void)
    func completeKeyActivation(challengeID: NSString, approvalSignature: NSData, withReply reply: @escaping (NSData?, NSError?) -> Void)
    func completeApprovalKeyActivation(challengeID: NSString, oldSignature: NSData, newSignature: NSData, withReply reply: @escaping (NSData?, NSError?) -> Void)
    func beginKeyAbort(role: NSString, generation: Int, reason: NSString, withReply reply: @escaping (NSData?, NSError?) -> Void)
    func completeKeyAbort(challengeID: NSString, approvalSignature: NSData, withReply reply: @escaping (NSData?, NSError?) -> Void)
    func beginKeyDeletion(role: NSString, generation: Int, reason: NSString, minimumRetentionSeconds: Int, proof: NSData, withReply reply: @escaping (NSData?, NSError?) -> Void)
    func completeKeyDeletion(challengeID: NSString, approvalSignature: NSData, withReply reply: @escaping (NSData?, NSError?) -> Void)
    func beginRecovery(role: NSString, withReply reply: @escaping (NSData?, NSError?) -> Void)
    func prepareRecoveryInstallation(evidence: NSData, withReply reply: @escaping (NSData?, NSError?) -> Void)
    func completeRecovery(challengeID: NSString, localSignature: NSData, withReply reply: @escaping (NSData?, NSError?) -> Void)
    func prepareAuditRecoveryInstallation(evidence: NSData, withReply reply: @escaping (NSData?, NSError?) -> Void)
    func completeAuditRecovery(challengeID: NSString, localSignature: NSData, withReply reply: @escaping (NSData?, NSError?) -> Void)
    func abortExpiredAuditRecovery(withReply reply: @escaping (NSData?, NSError?) -> Void)
    func auditRecoveryStatus(withReply reply: @escaping (NSData?, NSError?) -> Void)
    func auditAnchorStatus(withReply reply: @escaping (NSData?, NSError?) -> Void)
    func pushAuditAnchor(withReply reply: @escaping (NSData?, NSError?) -> Void)
    func prepareAuditPrune(request: NSData, withReply reply: @escaping (NSData?, NSError?) -> Void)
    func submitAuditPrune(withReply reply: @escaping (NSData?, NSError?) -> Void)
    func executeAuditPrune(withReply reply: @escaping (NSData?, NSError?) -> Void)
    func auditPruneStatus(withReply reply: @escaping (NSData?, NSError?) -> Void)
    func beginSession(agentID: NSString, ttlSeconds: Int, withReply reply: @escaping (NSData?, NSError?) -> Void)
    func completeSession(challenge: NSData, signature: NSData, withReply reply: @escaping (NSData?, NSError?) -> Void)
    func revokeSessions(withReply reply: @escaping (NSData?, NSError?) -> Void)
    func revokeSessions(agentID: NSString, withReply reply: @escaping (NSData?, NSError?) -> Void)
    func validateSession(token: NSString?, agentID: NSString, withReply reply: @escaping (Bool, NSError?) -> Void)
    func applyControlBundle(bundle: NSData, withReply reply: @escaping (NSData?, NSError?) -> Void)
    func controlStatus(withReply reply: @escaping (NSData?, NSError?) -> Void)
    func refreshControl(withReply reply: @escaping (NSData?, NSError?) -> Void)
    func validateControl(agentID: NSString, withReply reply: @escaping (Bool, NSError?) -> Void)
}
