BEGIN;
CREATE FUNCTION public.agentpass_publish_maintenance_advisory(p_advisory jsonb, p_payload_digest bytea, p_signature bytea, p_provider_id uuid, p_key_id text, p_version integer)
RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER VOLATILE SET search_path = pg_catalog, public AS $$ DECLARE aid uuid := (p_advisory->>'advisory_id')::uuid; BEGIN
  IF EXISTS (SELECT 1 FROM public.maintenance_provider_keys k WHERE k.provider_id=p_provider_id AND k.key_id=p_key_id AND k.purpose='advisory' AND k.compromised_at IS NULL AND k.valid_from<=clock_timestamp() AND (k.valid_until IS NULL OR k.valid_until>clock_timestamp())) IS NOT TRUE THEN RAISE EXCEPTION USING ERRCODE='insufficient_privilege', MESSAGE='provider key is not trusted'; END IF;
  INSERT INTO public.maintenance_advisories(advisory_id,provider_id,advisory_version,api_id,severity,released_at,enforcement_at,payload,payload_digest,signature,signing_key_id) VALUES(aid,p_provider_id,p_version,p_advisory->>'api_id',p_advisory->>'severity',(p_advisory->>'released_at')::timestamptz,NULLIF(p_advisory->>'enforcement_at','')::timestamptz,p_advisory,p_payload_digest,p_signature,p_key_id);
  INSERT INTO public.maintenance_advisory_events(advisory_id,event_type,event_payload) VALUES(aid,'publish',jsonb_build_object('digest',encode(p_payload_digest,'hex'))); RETURN aid;
END $$;
CREATE FUNCTION public.agentpass_supersede_maintenance_advisory(p_old uuid,p_new uuid,p_provider_id uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER VOLATILE SET search_path=pg_catalog,public AS $$ BEGIN IF NOT EXISTS (SELECT 1 FROM public.maintenance_providers p WHERE p.provider_id=p_provider_id AND p.status='active') OR NOT EXISTS (SELECT 1 FROM public.maintenance_advisories a WHERE a.advisory_id=p_old AND a.provider_id=p_provider_id AND a.state='published') OR NOT EXISTS (SELECT 1 FROM public.maintenance_advisories a WHERE a.advisory_id=p_new AND a.provider_id=p_provider_id AND a.state='published') THEN RAISE EXCEPTION USING ERRCODE='insufficient_privilege',MESSAGE='advisory provider binding is invalid'; END IF; UPDATE public.maintenance_advisories SET state='superseded' WHERE advisory_id=p_old AND provider_id=p_provider_id AND state='published'; UPDATE public.maintenance_advisories SET supersedes_advisory_id=p_old WHERE advisory_id=p_new AND provider_id=p_provider_id AND supersedes_advisory_id IS NULL; INSERT INTO public.maintenance_advisory_events(advisory_id,event_type,event_payload) VALUES(p_new,'supersede',jsonb_build_object('prior',p_old)); END $$;
CREATE FUNCTION public.agentpass_withdraw_maintenance_advisory(p_advisory uuid,p_reason text,p_provider_id uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER VOLATILE SET search_path=pg_catalog,public AS $$ BEGIN IF NOT EXISTS (SELECT 1 FROM public.maintenance_providers p JOIN public.maintenance_advisories a ON a.provider_id=p.provider_id WHERE p.provider_id=p_provider_id AND p.status='active' AND a.advisory_id=p_advisory AND a.state='published') THEN RAISE EXCEPTION USING ERRCODE='insufficient_privilege',MESSAGE='advisory provider binding is invalid'; END IF; UPDATE public.maintenance_advisories SET state='withdrawn' WHERE advisory_id=p_advisory AND provider_id=p_provider_id AND state='published'; INSERT INTO public.maintenance_advisory_events(advisory_id,event_type,event_payload) VALUES(p_advisory,'withdraw',jsonb_build_object('reason',left(p_reason,500))); END $$;
ALTER FUNCTION public.agentpass_publish_maintenance_advisory(jsonb,bytea,bytea,uuid,text,integer) OWNER TO agentpass_migrator; ALTER FUNCTION public.agentpass_supersede_maintenance_advisory(uuid,uuid,uuid) OWNER TO agentpass_migrator; ALTER FUNCTION public.agentpass_withdraw_maintenance_advisory(uuid,text,uuid) OWNER TO agentpass_migrator;
REVOKE ALL ON FUNCTION public.agentpass_publish_maintenance_advisory(jsonb,bytea,bytea,uuid,text,integer), public.agentpass_supersede_maintenance_advisory(uuid,uuid,uuid), public.agentpass_withdraw_maintenance_advisory(uuid,text,uuid) FROM PUBLIC,agentpass_app,agentpass_signer,agentpass_backup,agentpass_maintenance; GRANT EXECUTE ON FUNCTION public.agentpass_publish_maintenance_advisory(jsonb,bytea,bytea,uuid,text,integer), public.agentpass_supersede_maintenance_advisory(uuid,uuid,uuid), public.agentpass_withdraw_maintenance_advisory(uuid,text,uuid) TO agentpass_maintenance;
COMMIT;
