#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd -P)"
ROOT="$(cd "$SCRIPT_DIR/../../../../" && pwd -P)"
: "${AGENTPASS_QUALIFICATION_ARTIFACT:?AGENTPASS_QUALIFICATION_ARTIFACT is required}"
: "${AGENTPASS_QUALIFICATION_SOURCE_COMMIT:?AGENTPASS_QUALIFICATION_SOURCE_COMMIT is required}"
: "${AGENTPASS_QUALIFICATION_OUTPUT:?AGENTPASS_QUALIFICATION_OUTPUT is required}"
: "${AGENTPASS_LAUNCHD_HOST_CHILD_PROBE:?AGENTPASS_LAUNCHD_HOST_CHILD_PROBE is required}"
: "${AGENTPASS_NSXPC_PROBE:?AGENTPASS_NSXPC_PROBE is required}"
: "${AGENTPASS_CRASH_RESTART_PROBE:?AGENTPASS_CRASH_RESTART_PROBE is required}"
: "${AGENTPASS_QUALIFICATION_EXPECTED_ARCHITECTURE:?AGENTPASS_QUALIFICATION_EXPECTED_ARCHITECTURE is required}"

for value in "$AGENTPASS_QUALIFICATION_ARTIFACT" "$AGENTPASS_QUALIFICATION_OUTPUT" "$AGENTPASS_LAUNCHD_HOST_CHILD_PROBE" "$AGENTPASS_NSXPC_PROBE" "$AGENTPASS_CRASH_RESTART_PROBE"; do
  [[ "$value" == /* && "$value" != *$'\0'* ]] || { echo "qualification paths must be absolute" >&2; exit 1; }
done
[[ ! -e "$AGENTPASS_QUALIFICATION_OUTPUT" && ! -L "$AGENTPASS_QUALIFICATION_OUTPUT" ]] || { echo "qualification output already exists" >&2; exit 1; }
exec /usr/bin/env node "$ROOT/native/macos/Qualification/hardware-qualification.mjs" \
  --artifact "$AGENTPASS_QUALIFICATION_ARTIFACT" \
  --source-commit "$AGENTPASS_QUALIFICATION_SOURCE_COMMIT" \
  --expected-architecture "$AGENTPASS_QUALIFICATION_EXPECTED_ARCHITECTURE" \
  --output "$AGENTPASS_QUALIFICATION_OUTPUT" \
  --launchd-probe "$AGENTPASS_LAUNCHD_HOST_CHILD_PROBE" \
  --nsxpc-probe "$AGENTPASS_NSXPC_PROBE" \
  --crash-restart-probe "$AGENTPASS_CRASH_RESTART_PROBE"
