#!/bin/bash
set -euo pipefail
umask 077

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd -P)"
ROOT="$(cd "$SCRIPT_DIR/../../../../" && pwd -P)"
: "${AGENTPASS_QUALIFICATION_ARTIFACT:?AGENTPASS_QUALIFICATION_ARTIFACT is required}"
: "${AGENTPASS_QUALIFICATION_RELEASE_MANIFEST:?AGENTPASS_QUALIFICATION_RELEASE_MANIFEST is required}"
: "${AGENTPASS_QUALIFICATION_RELEASE_MANIFEST_SIGNATURE:?AGENTPASS_QUALIFICATION_RELEASE_MANIFEST_SIGNATURE is required}"
: "${AGENTPASS_QUALIFICATION_RELEASE_MANIFEST_PUBLIC_KEY:?AGENTPASS_QUALIFICATION_RELEASE_MANIFEST_PUBLIC_KEY is required}"
: "${AGENTPASS_QUALIFICATION_RELEASE_MANIFEST_FINGERPRINT:?AGENTPASS_QUALIFICATION_RELEASE_MANIFEST_FINGERPRINT is required}"
: "${AGENTPASS_QUALIFICATION_SOURCE_COMMIT:?AGENTPASS_QUALIFICATION_SOURCE_COMMIT is required}"
: "${AGENTPASS_QUALIFICATION_SOURCE_TREE:?AGENTPASS_QUALIFICATION_SOURCE_TREE is required}"
: "${AGENTPASS_QUALIFICATION_EXPECTED_TEAM_ID:?AGENTPASS_QUALIFICATION_EXPECTED_TEAM_ID is required}"
: "${AGENTPASS_QUALIFICATION_OUTPUT:?AGENTPASS_QUALIFICATION_OUTPUT is required}"
: "${AGENTPASS_RUNNER_ATTESTATION:?AGENTPASS_RUNNER_ATTESTATION is required}"
: "${AGENTPASS_RUNNER_ATTESTATION_SIGNATURE:?AGENTPASS_RUNNER_ATTESTATION_SIGNATURE is required}"
: "${AGENTPASS_RUNNER_ATTESTATION_PUBLIC_KEY:?AGENTPASS_RUNNER_ATTESTATION_PUBLIC_KEY is required}"
: "${AGENTPASS_RUNNER_ATTESTATION_FINGERPRINT:?AGENTPASS_RUNNER_ATTESTATION_FINGERPRINT is required}"
: "${AGENTPASS_LAUNCHD_HOST_CHILD_PROBE:?AGENTPASS_LAUNCHD_HOST_CHILD_PROBE is required}"
: "${AGENTPASS_NSXPC_PROBE:?AGENTPASS_NSXPC_PROBE is required}"
: "${AGENTPASS_CRASH_RESTART_PROBE:?AGENTPASS_CRASH_RESTART_PROBE is required}"
: "${AGENTPASS_QUALIFICATION_EXPECTED_ARCHITECTURE:?AGENTPASS_QUALIFICATION_EXPECTED_ARCHITECTURE is required}"

for value in "$AGENTPASS_QUALIFICATION_ARTIFACT" "$AGENTPASS_QUALIFICATION_RELEASE_MANIFEST" "$AGENTPASS_QUALIFICATION_RELEASE_MANIFEST_SIGNATURE" "$AGENTPASS_QUALIFICATION_RELEASE_MANIFEST_PUBLIC_KEY" "$AGENTPASS_QUALIFICATION_OUTPUT" "$AGENTPASS_RUNNER_ATTESTATION" "$AGENTPASS_RUNNER_ATTESTATION_SIGNATURE" "$AGENTPASS_RUNNER_ATTESTATION_PUBLIC_KEY" "$AGENTPASS_LAUNCHD_HOST_CHILD_PROBE" "$AGENTPASS_NSXPC_PROBE" "$AGENTPASS_CRASH_RESTART_PROBE"; do
  [[ "$value" == /* && "$value" != *$'\0'* ]] || { echo "qualification paths must be absolute" >&2; exit 1; }
done
[[ ! -e "$AGENTPASS_QUALIFICATION_OUTPUT" && ! -L "$AGENTPASS_QUALIFICATION_OUTPUT" ]] || { echo "qualification output already exists" >&2; exit 1; }
[[ "$AGENTPASS_QUALIFICATION_EXPECTED_TEAM_ID" =~ ^[A-Z0-9]{10}$ ]] || { echo "expected Developer ID Team ID is invalid" >&2; exit 1; }
[[ "$AGENTPASS_QUALIFICATION_EXPECTED_ARCHITECTURE" == arm64 || "$AGENTPASS_QUALIFICATION_EXPECTED_ARCHITECTURE" == x86_64 ]] || { echo "expected architecture is invalid" >&2; exit 1; }

exec /usr/bin/env node "$ROOT/native/macos/Qualification/hardware-qualification.mjs" \
  --artifact "$AGENTPASS_QUALIFICATION_ARTIFACT" \
  --release-manifest "$AGENTPASS_QUALIFICATION_RELEASE_MANIFEST" \
  --release-manifest-signature "$AGENTPASS_QUALIFICATION_RELEASE_MANIFEST_SIGNATURE" \
  --release-manifest-public-key "$AGENTPASS_QUALIFICATION_RELEASE_MANIFEST_PUBLIC_KEY" \
  --release-manifest-fingerprint "$AGENTPASS_QUALIFICATION_RELEASE_MANIFEST_FINGERPRINT" \
  --source-commit "$AGENTPASS_QUALIFICATION_SOURCE_COMMIT" \
  --source-tree "$AGENTPASS_QUALIFICATION_SOURCE_TREE" \
  --expected-team-id "$AGENTPASS_QUALIFICATION_EXPECTED_TEAM_ID" \
  --runner-attestation "$AGENTPASS_RUNNER_ATTESTATION" \
  --runner-attestation-signature "$AGENTPASS_RUNNER_ATTESTATION_SIGNATURE" \
  --runner-attestation-public-key "$AGENTPASS_RUNNER_ATTESTATION_PUBLIC_KEY" \
  --runner-attestation-fingerprint "$AGENTPASS_RUNNER_ATTESTATION_FINGERPRINT" \
  --expected-architecture "$AGENTPASS_QUALIFICATION_EXPECTED_ARCHITECTURE" \
  --output "$AGENTPASS_QUALIFICATION_OUTPUT" \
  --launchd-probe "$AGENTPASS_LAUNCHD_HOST_CHILD_PROBE" \
  --nsxpc-probe "$AGENTPASS_NSXPC_PROBE" \
  --crash-restart-probe "$AGENTPASS_CRASH_RESTART_PROBE"
