import test from "node:test";
import assert from "node:assert/strict";
import { canonicalDigest, canonicalJson, normalizeAppManifest, normalizeApplicationGrant, normalizeProviderOperation, parseStrictJson, redact, SmallSoftwareContractError } from "../src/index.mjs";

const ids = ["11111111-1111-4111-8111-111111111111","22222222-2222-4222-8222-222222222222","33333333-3333-4333-8333-333333333333","44444444-4444-4444-8444-444444444444","55555555-5555-4555-8555-555555555555"];
const manifest = { version:1, kind:"agentpass.app-manifest", name:"sales-follow-up", runtime:"cloudflare-worker", entrypoint:"dist/worker.js", static_assets:"dist/public", data:[], egress:[{origin:"https://api.example.com",methods:["GET"]}], connections:[], schedules:[], health_path:"/_agentpass/health" };
test("normalizes the canonical manifest and digest is key-order independent",()=>{ const a=normalizeAppManifest(manifest); const b=normalizeAppManifest({...manifest,egress:[{methods:["GET"],origin:"https://api.example.com"}]}); assert.equal(canonicalDigest(a),canonicalDigest(b)); assert.equal(canonicalJson(a),canonicalJson(b)); });
test("closed schemas reject aliases, traversal, origins, and noncanonical times",()=>{ for (const bad of [{...manifest,extra:true},{...manifest,entrypoint:"../worker.js"},{...manifest,egress:[{origin:"http://api.example.com",methods:["GET"]}]},{...manifest,createdAt:"2026-01-01T00:00:00.000Z"}]) assert.throws(()=>normalizeAppManifest(bad),SmallSoftwareContractError); });
test("grant is purpose-separated and agent operations are bounded",()=>{ const grant={version:1,kind:"agentpass.application-grant",grant_id:ids[0],organization_id:ids[1],app_id:ids[2],actor_id:ids[3],session_id:ids[4],operations:["app.preview.prepare"],issued_at:"2026-01-01T00:00:00.000Z",expires_at:"2026-01-01T00:05:00.000Z",signing_purpose:"small-software.application-grant",key_id:"ss-grant-v1",request_digest:"a".repeat(64)}; assert.equal(normalizeApplicationGrant(grant).signing_purpose,"small-software.application-grant"); assert.throws(()=>normalizeApplicationGrant({...grant,operations:["app.release.activate"]}),SmallSoftwareContractError); });
test("provider operation rejects request digest substitution and unsafe idempotency",()=>{ const op={version:1,kind:"agentpass.provider-operation",operation_id:ids[0],organization_id:ids[1],app_id:ids[2],provider:"cloudflare",operation:"deploy",request_digest:"a".repeat(64),idempotency_key:"deploy-1234",state:"pending",created_at:"2026-01-01T00:00:00.000Z"}; assert.equal(normalizeProviderOperation(op).state,"pending"); assert.throws(()=>normalizeProviderOperation({...op,request_digest:"b".repeat(63)+"!"}),SmallSoftwareContractError); assert.throws(()=>normalizeProviderOperation({...op,idempotency_key:"short"}),SmallSoftwareContractError); });
test("redaction removes secret-like values without exposing replacement bytes",()=>{ const out=redact({token:"do-not-return",nested:{password:"x",ok:"yes"}}); assert.deepEqual(out,{nested:{ok:"yes"}}); });
test("strict JSON rejects duplicates only within the same object scope",()=>{ assert.deepEqual(parseStrictJson('{"a":{"x":1},"b":{"x":2}}'),{a:{x:1},b:{x:2}}); assert.throws(()=>parseStrictJson('{"a":1,"a":2}'),SmallSoftwareContractError); });
