import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import { validateProviderIdentity, validateAdvisory, validateSelector, validateMaintenancePolicy, validateMaintenanceGrant, canonicalJson, signAdvisory, verifyAdvisory, advisoryDigest, MaintenanceContractError } from '../src/index.mjs';

const fixture = (name) => JSON.parse(fs.readFileSync(new URL(`../../../contracts/fixtures/${name}`, import.meta.url)));
test('valid provider and advisory fixtures validate', () => { validateProviderIdentity(fixture('maintenance-provider-identity.valid.json')); const a = fixture('maintenance-advisory-endpoint.valid.json'); validateAdvisory(a); assert.equal(advisoryDigest(a).length, 64); });
test('canonical JSON is deterministic and sorted', () => { assert.equal(canonicalJson({ z: 1, a: { y: true, x: 2 } }), '{"a":{"x":2,"y":true},"z":1}'); });
test('all eight selector classes are accepted', () => { const xs = JSON.parse(fs.readFileSync(new URL('../../../test/fixtures/sample-api-provider/advisories.json', import.meta.url))); for (const x of xs) validateSelector(x.selector); });
test('selectors and provider origins fail closed', () => { assert.throws(() => validateSelector({ type: 'endpoint', path: '/v1/*' }), (e) => e.code === 'overbroad_selector'); assert.throws(() => validateSelector({ type: 'endpoint', path: '/v1/../admin' }), (e) => e.code === 'overbroad_selector'); assert.throws(() => validateProviderIdentity({ ...fixture('maintenance-provider-identity.valid.json'), publisher_origin: 'http://provider.example' }), (e) => e.code === 'invalid_origin'); });
test('unknown fields, versions and executable attachments fail closed', () => { const a = fixture('maintenance-advisory-endpoint.valid.json'); assert.throws(() => validateAdvisory({ ...a, extra: true }), (e) => e.code === 'unknown_field'); assert.throws(() => validateAdvisory({ ...a, schema_version: 2 }), (e) => e.code === 'unknown_version'); assert.throws(() => validateAdvisory({ ...a, migration_attachment: { uri: 'https://provider.example/migrate', digest: 'a'.repeat(64), media_type: 'text/plain', executable: true } }), (e) => e.code === 'executable_attachment'); });
test('provider authority cannot select app/repository or approval', () => { assert.throws(() => validateMaintenanceGrant({ ...fixture('maintenance-grant.valid.json'), provider_id: 'sample.api' }), (e) => e.code === 'provider_authority_boundary'); assert.throws(() => validateMaintenanceGrant({ ...fixture('maintenance-grant.valid.json'), operations: ['approve'] }), (e) => e.code === 'invalid_grant'); });
test('correction and withdrawal are new events with distinct IDs/sequences', () => { const a = fixture('maintenance-advisory-endpoint.valid.json'); const correction = { ...a, advisory_id: 'adv-endpoint-2', sequence: 2, event: 'correction' }; const withdrawal = { ...a, advisory_id: 'adv-endpoint-3', sequence: 3, event: 'withdrawal' }; validateAdvisory(correction); validateAdvisory(withdrawal); assert.notEqual(a.advisory_id, correction.advisory_id); });
test('purpose separation signs only advisory domain', () => { const a = fixture('maintenance-advisory-endpoint.valid.json'); const keys = crypto.generateKeyPairSync('ed25519'); const signature = signAdvisory(a, keys.privateKey); assert.equal(verifyAdvisory(a, signature, keys.publicKey), true); assert.equal(verifyAdvisory({ ...a, event: 'correction', advisory_id: 'other', sequence: 2 }, signature, keys.publicKey), false); });
test('policy is bounded to private-alpha modes and exact paths', () => { validateMaintenancePolicy(fixture('maintenance-policy.valid.json')); assert.throws(() => validateMaintenancePolicy({ ...fixture('maintenance-policy.valid.json'), mode: 'auto_merge' }), (e) => e.code === 'invalid_policy'); assert.throws(() => validateMaintenancePolicy({ ...fixture('maintenance-policy.valid.json'), allowed_paths: ['/src/*'] }), (e) => e.code === 'overbroad_policy'); });
