import assert from 'node:assert/strict';
import test from 'node:test';
import { validateXpcQualificationEvidence } from './verify-xpc-qualification.mjs';
const digest = (character) => character.repeat(64);
const evidence = () => ({ schema_version: 1, candidate_sha256: digest('a'), source_commit: '0123456789abcdef0123456789abcdef01234567', host_activation: { audit_token_capture: 'live_eight_field', audit_token_sha256: digest('b'), child_process_identity_sha256: digest('c'), child_requirement_sha256: digest('d'), projection_sha256: digest('e'), status: 'passed', transport: 'authenticated_xpc' }, child_requirement: { evaluation: 'passed', principal: 'dev.agentpass.git-sign-xpc', sha256: digest('d') }, negative_cases: [{ case: 'same_uid_wrong_child', result: 'denied_before_sign' }, { case: 'wrong_team', result: 'denied_before_sign' }, { case: 'wrong_entitlement', result: 'denied_before_sign' }, { case: 'stale_or_reused_audit_token', result: 'denied_before_sign' }] });
test('accepts a closed candidate-bound Host activation projection', () => { const result = validateXpcQualificationEvidence(evidence()); assert.equal(result.candidate_sha256, digest('a')); assert.match(result.evidence_sha256, /^[0-9a-f]{64}$/u); });
test('requires Child-specific requirement digest equality', () => { const value = evidence(); value.child_requirement.sha256 = digest('f'); assert.throws(() => validateXpcQualificationEvidence(value), /not bound to Host activation/u); });
test('requires live authenticated transport and all denial cases', () => { const value = evidence(); value.host_activation.transport = 'legacy_fd3'; assert.throws(() => validateXpcQualificationEvidence(value), /authenticated_xpc/u); const incomplete = evidence(); incomplete.negative_cases.pop(); assert.throws(() => validateXpcQualificationEvidence(incomplete), /fixed denial matrix/u); });
test('rejects raw token or secret-bearing evidence fields', () => { const value = evidence(); value.raw_token = 'must-not-be-recorded'; assert.throws(() => validateXpcQualificationEvidence(value), /unknown fields/u); });
