import crypto from 'node:crypto';

export const MAINTENANCE_CONTRACT_VERSION = 1;
export const ADVISORY_SIGNATURE_DOMAIN = 'agentpass.maintenance.advisory/v1';
export const EVENT_SIGNATURE_DOMAIN = 'agentpass.maintenance.provider-key-event/v1';
const ID = /^[A-Za-z0-9][A-Za-z0-9._:/-]{0,127}$/;
const DIGEST = /^[0-9a-f]{64}$/;
const TS = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/;
const PATH = /^\/(?:[^\0\n\r]+)$/;
const METHODS = new Set(['GET','POST','PUT','PATCH','DELETE','HEAD','OPTIONS']);
const SELECTOR_TYPES = new Set(['endpoint','method','field','sdk_symbol','pagination','version_header','webhook_field','error']);
const IMPACT_CLASSIFICATIONS = new Set(['confirmed','probable','possible','not_affected','unknown']);
const JOB_STATES = new Set(['impact_detected','planned','authorized','workspace_preparing','patching','verifying','pr_creating','pr_open','awaiting_customer','merged','release_preparing','deployed','post_deploy_verified','completed','not_affected','ignored','cancelled','patch_failed','verification_failed','pr_failed','provider_operation_uncertain','superseded','merge_failed','deployment_failed','rolled_back','manual_action_required']);
const EFFECT_KINDS = new Set(['snapshot_read','patch_propose','branch_create','pull_request_create','test_execute','conformance_execute']);
const EFFECT_STATES = new Set(['reserved','started','accepted','completed','cancelled','uncertain','failed']);
const RESULT_STATES = new Set(['passed','failed','uncertain']);
const PR_STATES = new Set(['draft','open','closed','merged']);

export class MaintenanceContractError extends Error { constructor(code, message) { super(message); this.name = 'MaintenanceContractError'; this.code = code; } }
const fail = (code, message) => { throw new MaintenanceContractError(code, message); };
function object(value, label) { if (!value || typeof value !== 'object' || Array.isArray(value)) fail('invalid_object', `${label} must be an object`); return value; }
function closed(value, allowed, label) { for (const key of Object.keys(value)) if (!allowed.has(key)) fail('unknown_field', `${label} contains an unknown field`); }
function id(value, label) { if (typeof value !== 'string' || !ID.test(value)) fail('invalid_identifier', `${label} is invalid`); return value; }
function digest(value, label) { if (typeof value !== 'string' || !DIGEST.test(value)) fail('invalid_digest', `${label} is invalid`); return value; }
function timestamp(value, label) { if (typeof value !== 'string' || !TS.test(value) || Number.isNaN(Date.parse(value))) fail('invalid_timestamp', `${label} is invalid`); return value; }

export function canonicalJson(value) {
  const seen = new Set();
  const walk = (v) => {
    if (v === null || typeof v === 'string' || typeof v === 'boolean') return JSON.stringify(v);
    if (typeof v === 'number' && Number.isFinite(v)) return JSON.stringify(v);
    if (!v || typeof v !== 'object' || seen.has(v)) fail('noncanonical_value', 'value is not canonical JSON');
    seen.add(v);
    const out = Array.isArray(v) ? `[${v.map(walk).join(',')}]` : `{${Object.keys(v).sort().map(k => `${JSON.stringify(k)}:${walk(v[k])}`).join(',')}}`;
    seen.delete(v); return out;
  }; return walk(value);
}
export const canonicalize = canonicalJson;
export function sha256(value) { return crypto.createHash('sha256').update(typeof value === 'string' ? value : canonicalJson(value)).digest('hex'); }

export function validateProviderIdentity(value) {
  const v = object(value, 'provider'); closed(v, new Set(['schema_version','kind','provider_id','display_name','publisher_origin','identity_digest','key_ids']), 'provider');
  if (v.schema_version !== 1 || v.kind !== 'agentpass.maintenance.provider-identity') fail('unknown_version', 'unsupported provider contract');
  id(v.provider_id, 'provider_id'); if (typeof v.display_name !== 'string' || !v.display_name || v.display_name.length > 200) fail('invalid_display_name', 'display_name is invalid');
  if (typeof v.publisher_origin !== 'string' || !/^https:\/\/[^/\s]+$/.test(v.publisher_origin)) fail('invalid_origin', 'publisher_origin must be HTTPS origin'); digest(v.identity_digest, 'identity_digest');
  if (!Array.isArray(v.key_ids) || !v.key_ids.length || v.key_ids.length > 32 || new Set(v.key_ids).size !== v.key_ids.length) fail('invalid_keys', 'key_ids must be unique and bounded'); v.key_ids.forEach((x) => id(x, 'key_id')); return v;
}

export function validateSelector(value) {
  const v = object(value, 'selector'); closed(v, new Set(['type','operation','path','field','symbol','from','to']), 'selector');
  if (!SELECTOR_TYPES.has(v.type)) fail('invalid_selector', 'unknown selector type');
  if (v.operation !== undefined && !METHODS.has(v.operation)) fail('invalid_selector', 'invalid method');
  if (v.path !== undefined && (typeof v.path !== 'string' || !PATH.test(v.path) || v.path.includes('*') || v.path.includes('..'))) fail('overbroad_selector', 'path selector must be exact and absolute');
  for (const k of ['field','symbol','from','to']) if (v[k] !== undefined && (typeof v[k] !== 'string' || !v[k].length || v[k].length > 200 || /[*\n\r]/.test(v[k]))) fail('invalid_selector', `${k} is invalid`);
  if (v.type === 'endpoint' && (!v.path || v.operation)) fail('invalid_selector', 'endpoint requires exact path only');
  if (v.type === 'method' && (!v.path || !v.operation)) fail('invalid_selector', 'method requires exact path and method');
  if (['field','webhook_field'].includes(v.type) && (!v.path || !v.field)) fail('invalid_selector', 'field requires exact path and field');
  if (v.type === 'sdk_symbol' && !v.symbol) fail('invalid_selector', 'SDK symbol is required');
  if (['pagination', 'version_header', 'error'].includes(v.type) && (!v.path || !v.from || !v.to)) fail('invalid_selector', `${v.type} requires exact path and from/to values`);
  return v;
}

export function validateAdvisory(value) {
  const v = object(value, 'advisory'); closed(v, new Set(['schema_version','kind','advisory_id','provider_id','provider_key_id','sequence','event','severity','published_at','effective_at','selectors','old_contract_digest','new_contract_digest','migration_attachment','statement_digest','signature_algorithm','signature']), 'advisory');
  if (v.schema_version !== 1 || v.kind !== 'agentpass.maintenance.advisory') fail('unknown_version', 'unsupported advisory contract'); id(v.advisory_id, 'advisory_id'); id(v.provider_id, 'provider_id'); id(v.provider_key_id, 'provider_key_id');
  if (!Number.isSafeInteger(v.sequence) || v.sequence < 1) fail('invalid_sequence', 'sequence must be positive'); if (!['publish','correction','withdrawal'].includes(v.event)) fail('invalid_event', 'event is invalid'); if (!['low','medium','high','critical'].includes(v.severity)) fail('invalid_severity', 'severity is invalid'); timestamp(v.published_at, 'published_at'); timestamp(v.effective_at, 'effective_at');
  if (Date.parse(v.effective_at) < Date.parse(v.published_at)) fail('invalid_time_order', 'effective_at precedes publication'); if (!Array.isArray(v.selectors) || !v.selectors.length || v.selectors.length > 64) fail('invalid_selectors', 'selectors are bounded'); if (new Set(v.selectors.map(x => canonicalJson(validateSelector(x)))).size !== v.selectors.length) fail('duplicate_selector', 'selectors must be unique');
  v.selectors.forEach(validateSelector); digest(v.old_contract_digest, 'old_contract_digest'); digest(v.new_contract_digest, 'new_contract_digest'); if (v.migration_attachment !== undefined) { const a = object(v.migration_attachment, 'migration_attachment'); closed(a, new Set(['uri','digest','media_type','executable']), 'migration_attachment'); if (a.executable !== false) fail('executable_attachment', 'executable migration material is never trusted'); if (typeof a.uri !== 'string' || !/^https:\/\//.test(a.uri)) fail('invalid_attachment', 'attachment URI must be HTTPS'); digest(a.digest, 'attachment digest'); if (typeof a.media_type !== 'string' || a.media_type.length > 128) fail('invalid_attachment', 'attachment media type invalid'); }
  if (v.statement_digest !== undefined) digest(v.statement_digest, 'statement_digest'); if (v.signature_algorithm !== 'ed25519' || typeof v.signature !== 'string' || !/^[A-Za-z0-9_-]{86}$/.test(v.signature)) fail('invalid_signature', 'signature is invalid'); return v;
}

export function validateProviderKeyEvent(value) { const v = object(value, 'provider key event'); closed(v, new Set(['schema_version','kind','event_id','provider_id','provider_key_id','event','reason','occurred_at','statement_digest','signature_algorithm','signature']), 'provider key event'); if (v.schema_version !== 1 || v.kind !== 'agentpass.maintenance.provider-key-event') fail('unknown_version', 'unsupported key event'); id(v.event_id, 'event_id'); id(v.provider_id, 'provider_id'); id(v.provider_key_id, 'provider_key_id'); if (!['activate','revoke','rotate'].includes(v.event)) fail('invalid_event', 'event is invalid'); if (typeof v.reason !== 'string' || !v.reason || v.reason.length > 500) fail('invalid_reason', 'reason is invalid'); timestamp(v.occurred_at, 'occurred_at'); digest(v.statement_digest, 'statement_digest'); if (v.signature_algorithm !== 'ed25519' || typeof v.signature !== 'string' || !/^[A-Za-z0-9_-]{86}$/.test(v.signature)) fail('invalid_signature', 'signature is invalid'); return v; }

export function validateUsageAttestation(v) { const x = validateSimple(v, 'agentpass.maintenance.usage-attestation', new Set(['schema_version','kind','attestation_id','organization_id','app_id','provider_id','snapshot_id','release_id','source_commit','source_digest','observed_at','fresh_until','classification','confidence','evidence','result_digest','usages']), ['schema_version','kind','attestation_id','organization_id','app_id','provider_id','source_digest','observed_at','usages']); timestamp(x.observed_at, 'observed_at'); if (!Array.isArray(x.usages) || x.usages.length > 256) fail('invalid_usages', 'usages must be a bounded array'); x.usages.forEach((usage) => { const item = object(usage, 'usage'); closed(item, new Set(['selector','file','line']), 'usage'); if (typeof item.selector !== 'string' || item.selector.length === 0 || item.selector.length > 256) fail('invalid_usages', 'usage selector is invalid'); if (typeof item.file !== 'string' || !PATH.test(item.file) || item.file.includes('..') || item.file.includes('*')) fail('invalid_usages', 'usage file is invalid'); if (!Number.isSafeInteger(item.line) || item.line < 1 || item.line > 10000000) fail('invalid_usages', 'usage line is invalid'); }); return x; }
export function validateRepositorySnapshot(v) { const x = validateSimple(v, 'agentpass.maintenance.repository-snapshot', new Set(['schema_version','kind','snapshot_id','organization_id','app_id','repository_id','repository_name','default_branch','branch','base_commit','tree_digest','source_digest','active_release_id','usage_index_digest','captured_at']), ['schema_version','kind','snapshot_id','organization_id','repository_id','repository_name','default_branch','base_commit','captured_at']); for (const key of ['repository_name','default_branch','branch','base_commit','active_release_id']) if (x[key] !== undefined && (typeof x[key] !== 'string' || x[key].length === 0 || x[key].length > 256 || /[\0\n\r]/.test(x[key]))) fail('invalid_snapshot', `${key} is invalid`); for (const key of ['tree_digest','source_digest','usage_index_digest']) if (x[key] !== undefined) digest(x[key], key); timestamp(x.captured_at, 'captured_at'); return x; }
export function validateUsageClassification(v) { const x = validateUsageAttestation(v); const allowed = new Set(['schema_version','kind','attestation_id','organization_id','app_id','provider_id','snapshot_id','release_id','source_commit','source_digest','observed_at','fresh_until','classification','confidence','evidence','result_digest','usages']); closed(x, allowed, 'agentpass.maintenance.usage-attestation'); if (x.snapshot_id !== undefined) id(x.snapshot_id, 'snapshot_id'); if (x.release_id !== undefined) id(x.release_id, 'release_id'); if (x.source_commit !== undefined && (typeof x.source_commit !== 'string' || x.source_commit.length === 0 || x.source_commit.length > 256)) fail('invalid_usages', 'source_commit is invalid'); if (x.classification !== undefined && !IMPACT_CLASSIFICATIONS.has(x.classification)) fail('invalid_classification', 'classification is invalid'); if (x.confidence !== undefined && (!Number.isFinite(x.confidence) || x.confidence < 0 || x.confidence > 1)) fail('invalid_classification', 'confidence must be between 0 and 1'); if (x.evidence !== undefined) { object(x.evidence, 'evidence'); if (canonicalJson(x.evidence).length > 32_768) fail('invalid_classification', 'evidence is too large'); } if (x.result_digest !== undefined) digest(x.result_digest, 'result_digest'); if (x.fresh_until !== undefined) timestamp(x.fresh_until, 'fresh_until'); return x; }
export function validateMaintenancePolicy(v) { const x = validateSimple(v, 'agentpass.maintenance.policy', new Set(['schema_version','kind','policy_id','organization_id','generation','mode','allowed_provider_ids','allowed_branches','allowed_paths','max_files','expires_at']), ['schema_version','kind','policy_id','organization_id','mode','allowed_provider_ids','allowed_branches','allowed_paths','max_files','expires_at']); if (!['notify','draft_pr'].includes(x.mode)) fail('invalid_policy', 'private-alpha supports notify and draft_pr only'); if (x.generation !== undefined && (!Number.isSafeInteger(x.generation) || x.generation < 1)) fail('invalid_policy', 'generation is invalid'); if (!Array.isArray(x.allowed_provider_ids) || !Array.isArray(x.allowed_branches) || !Array.isArray(x.allowed_paths)) fail('invalid_policy', 'policy arrays required'); x.allowed_paths.forEach((p) => { if (!PATH.test(p) || p.includes('*') || p.includes('..')) fail('overbroad_policy', 'paths must be exact'); }); if (!Number.isSafeInteger(x.max_files) || x.max_files < 1 || x.max_files > 1000) fail('invalid_policy', 'max_files is invalid'); timestamp(x.expires_at, 'expires_at'); return x; }
export function validateMaintenancePlan(v) { const x = validateSimple(v, 'agentpass.maintenance.plan', new Set(['schema_version','kind','plan_id','organization_id','app_id','repository_id','branch','advisory_id','snapshot_id','usage_attestation_id','base_commit','active_release_id','policy_id','policy_generation','plan_digest','selector_digests','files','authority','created_at','expires_at','idempotency_key']), ['schema_version','kind','plan_id','organization_id','app_id','repository_id','branch','advisory_id','selector_digests','files','authority']); for (const key of ['snapshot_id','usage_attestation_id','policy_id']) if (x[key] !== undefined) id(x[key], key); for (const key of ['base_commit','active_release_id','branch','idempotency_key']) if (x[key] !== undefined && (typeof x[key] !== 'string' || x[key].length === 0 || x[key].length > 256 || /[\0\n\r]/.test(x[key]))) fail('invalid_plan', `${key} is invalid`); if (x.policy_generation !== undefined && (!Number.isSafeInteger(x.policy_generation) || x.policy_generation < 1)) fail('invalid_plan', 'policy_generation is invalid'); if (x.plan_digest !== undefined) digest(x.plan_digest, 'plan_digest'); if (x.created_at !== undefined) timestamp(x.created_at, 'created_at'); if (x.expires_at !== undefined) timestamp(x.expires_at, 'expires_at'); if (!Array.isArray(x.selector_digests) || x.selector_digests.length < 1 || x.selector_digests.length > 64) fail('invalid_plan', 'selector_digests must be bounded and non-empty'); x.selector_digests.forEach((value) => digest(value, 'selector_digest')); if (!Array.isArray(x.files) || x.files.length < 1 || x.files.length > 256) fail('invalid_plan', 'files must be bounded and non-empty'); x.files.forEach((value) => { if (typeof value !== 'string' || !PATH.test(value) || value.includes('..') || value.includes('*')) fail('invalid_plan', 'files must be exact absolute paths'); }); const authority = object(x.authority, 'authority'); closed(authority, new Set(['purpose','operations']), 'authority'); if (authority.purpose !== 'agentpass.maintenance.plan' || !Array.isArray(authority.operations) || authority.operations.length < 1 || authority.operations.some((value) => !['read_source','write_patch','run_tests','create_draft_pr'].includes(value))) fail('invalid_plan', 'authority is not bounded'); return x; }
export function validateMaintenanceJob(v) { const x = validateSimple(v, 'agentpass.maintenance.job', new Set(['schema_version','kind','job_id','organization_id','app_id','repository_id','branch','provider_id','advisory_id','snapshot_id','usage_attestation_id','policy_id','policy_generation','plan_id','plan_digest','status','created_at','updated_at','idempotency_key']), ['schema_version','kind','job_id','organization_id','repository_id','provider_id','advisory_id','snapshot_id','plan_id','plan_digest','status','created_at']); for (const key of ['snapshot_id','usage_attestation_id','policy_id','plan_id']) if (x[key] !== undefined) id(x[key], key); digest(x.plan_digest, 'plan_digest'); if (!JOB_STATES.has(x.status)) fail('invalid_job', 'status is invalid'); if (x.branch !== undefined && (typeof x.branch !== 'string' || !x.branch.length || /[\0\n\r]/.test(x.branch))) fail('invalid_job', 'branch is invalid'); timestamp(x.created_at, 'created_at'); if (x.updated_at !== undefined) timestamp(x.updated_at, 'updated_at'); if (x.policy_generation !== undefined && (!Number.isSafeInteger(x.policy_generation) || x.policy_generation < 1)) fail('invalid_job', 'policy_generation is invalid'); return x; }
export function validateMaintenanceEffect(v) { const x = validateSimple(v, 'agentpass.maintenance.effect', new Set(['schema_version','kind','effect_id','job_id','organization_id','effect_kind','idempotency_key','state','request_digest','response_digest','reserved_at','completed_at']), ['schema_version','kind','effect_id','job_id','organization_id','effect_kind','idempotency_key','state','request_digest','reserved_at']); if (!EFFECT_KINDS.has(x.effect_kind)) fail('invalid_effect', 'effect_kind is invalid'); if (!EFFECT_STATES.has(x.state)) fail('invalid_effect', 'state is invalid'); if (typeof x.idempotency_key !== 'string' || !x.idempotency_key || x.idempotency_key.length > 256) fail('invalid_effect', 'idempotency_key is invalid'); digest(x.request_digest, 'request_digest'); if (x.response_digest !== undefined && x.response_digest !== null) digest(x.response_digest, 'response_digest'); timestamp(x.reserved_at, 'reserved_at'); if (x.completed_at !== undefined && x.completed_at !== null) timestamp(x.completed_at, 'completed_at'); return x; }
export function validateMaintenanceResult(v) { const x = validateSimple(v, 'agentpass.maintenance.result', new Set(['schema_version','kind','result_id','job_id','organization_id','source_commit','result_commit','result_tree','patch_digest','result_digest','changed_paths','evidence','status','verification_status','created_at']), ['schema_version','kind','result_id','job_id','organization_id','status','created_at']); if (!RESULT_STATES.has(x.status)) fail('invalid_result', 'status is invalid'); for (const key of ['source_commit','result_commit','result_tree']) if (x[key] !== undefined && (typeof x[key] !== 'string' || !x[key].length || x[key].length > 256)) fail('invalid_result', `${key} is invalid`); if (x.patch_digest !== undefined && x.patch_digest !== null) digest(x.patch_digest, 'patch_digest'); if (x.result_digest !== undefined && x.result_digest !== null) digest(x.result_digest, 'result_digest'); if (x.changed_paths !== undefined) { if (!Array.isArray(x.changed_paths) || x.changed_paths.length > 256) fail('invalid_result', 'changed_paths is invalid'); x.changed_paths.forEach((p) => { if (typeof p !== 'string' || !PATH.test(p) || p.includes('..') || p.includes('*')) fail('invalid_result', 'changed_paths must be exact'); }); } if (x.evidence !== undefined) { object(x.evidence, 'evidence'); if (canonicalJson(x.evidence).length > 32_768) fail('invalid_result', 'evidence is too large'); } if (x.verification_status !== undefined && !['passed','partial','failed','not_run'].includes(x.verification_status)) fail('invalid_result', 'verification_status is invalid'); timestamp(x.created_at, 'created_at'); return x; }
export function validatePatchProposal(v) {
  const x = validateSimple(v, 'agentpass.maintenance.patch-proposal', new Set(['schema_version','kind','proposal_id','organization_id','app_id','repository_id','job_id','plan_id','advisory_id','base_commit','branch','changed_paths','patch_digest','diff_digest','changes','tests','conformance','verification_status','uncertainty','created_at','authority']), ['schema_version','kind','proposal_id','organization_id','repository_id','job_id','plan_id','advisory_id','base_commit','branch','changed_paths','patch_digest','diff_digest','changes','tests','conformance','verification_status','uncertainty','created_at','authority']);
  for (const key of ['base_commit','branch']) if (typeof x[key] !== 'string' || !x[key].length || x[key].length > 256 || /[\0\n\r]/u.test(x[key])) fail('invalid_patch_proposal', `${key} is invalid`);
  digest(x.patch_digest, 'patch_digest'); digest(x.diff_digest, 'diff_digest');
  if (!Array.isArray(x.changed_paths) || x.changed_paths.length < 1 || x.changed_paths.length > 100 || new Set(x.changed_paths).size !== x.changed_paths.length) fail('invalid_patch_proposal', 'changed_paths are invalid');
  x.changed_paths.forEach((p) => { if (typeof p !== 'string' || !PATH.test(p) || p.includes('..') || p.includes('*')) fail('invalid_patch_proposal', 'changed_paths must be exact'); });
  if (!Array.isArray(x.changes) || x.changes.length !== x.changed_paths.length || x.changes.length > 100) fail('invalid_patch_proposal', 'changes are invalid');
  x.changes.forEach((change) => { const c = object(change, 'patch change'); closed(c, new Set(['path','operation','before_digest','after_digest','diff']), 'patch change'); if (!x.changed_paths.includes(c.path) || !['add','modify','delete'].includes(c.operation) || typeof c.diff !== 'string' || !c.diff.length || c.diff.length > 512 * 1024) fail('invalid_patch_proposal', 'patch change is invalid'); if (c.before_digest !== null) digest(c.before_digest, 'before_digest'); if (c.after_digest !== null) digest(c.after_digest, 'after_digest'); });
  if (!Array.isArray(x.tests) || x.tests.length > 64 || x.tests.some((item) => !item || typeof item.id !== 'string' || typeof item.kind !== 'string' || item.status !== 'not_run')) fail('invalid_patch_proposal', 'tests must be explicit not_run descriptors');
  if (!Array.isArray(x.conformance) || x.conformance.length > 32 || x.conformance.some((item) => !item || typeof item.id !== 'string' || item.status !== 'not_proven')) fail('invalid_patch_proposal', 'conformance must be explicit not_proven descriptors');
  if (!['not_run','partial'].includes(x.verification_status)) fail('invalid_patch_proposal', 'verification_status must not claim verification');
  if (!Array.isArray(x.uncertainty) || x.uncertainty.length < 1 || x.uncertainty.length > 64 || x.uncertainty.some((item) => typeof item !== 'string' || item.length > 500)) fail('invalid_patch_proposal', 'uncertainty is invalid');
  const authority = object(x.authority, 'authority'); closed(authority, new Set(['operations','shell','credentials','network']), 'authority'); if (JSON.stringify(authority.operations) !== JSON.stringify(['read_source','write_patch']) || authority.shell !== false || authority.credentials !== false || authority.network !== false) fail('invalid_patch_proposal', 'authority is not bounded');
  timestamp(x.created_at, 'created_at'); return x;
}
export function validateMaintenancePullRequest(v) { const x = validateSimple(v, 'agentpass.maintenance.pull-request', new Set(['schema_version','kind','pull_request_id','job_id','organization_id','repository_id','external_number','head_commit','base_commit','head_branch','base_branch','state','url','created_at','updated_at']), ['schema_version','kind','pull_request_id','job_id','organization_id','repository_id','external_number','head_commit','base_commit','state','created_at']); if (!Number.isSafeInteger(x.external_number) || x.external_number < 1) fail('invalid_pull_request', 'external_number is invalid'); if (!PR_STATES.has(x.state)) fail('invalid_pull_request', 'state is invalid'); for (const key of ['head_commit','base_commit','head_branch','base_branch','url']) if (x[key] !== undefined && (typeof x[key] !== 'string' || !x[key].length || x[key].length > 2048 || /[\0\n\r]/.test(x[key]))) fail('invalid_pull_request', `${key} is invalid`); timestamp(x.created_at, 'created_at'); if (x.updated_at !== undefined) timestamp(x.updated_at, 'updated_at'); return x; }
export const validateMaintenancePr = validateMaintenancePullRequest;
export function validateMaintenanceGrant(v) { const x = validateSimple(v, 'agentpass.maintenance.grant', new Set(['schema_version','kind','grant_id','organization_id','repository_id','branch','job_id','issued_at','expires_at','operations','provider_id']), ['schema_version','kind','grant_id','organization_id','repository_id','branch','job_id','issued_at','expires_at','operations']); if (x.provider_id !== undefined) fail('provider_authority_boundary', 'provider cannot select grant authority'); if (!Array.isArray(x.operations) || x.operations.length < 1 || x.operations.length > 8 || x.operations.some(o => !['read_source','write_patch','run_tests','create_draft_pr'].includes(o)) || new Set(x.operations).size !== x.operations.length) fail('invalid_grant', 'grant operations are not bounded'); timestamp(x.issued_at, 'issued_at'); timestamp(x.expires_at, 'expires_at'); if (Date.parse(x.expires_at) <= Date.parse(x.issued_at)) fail('invalid_grant', 'grant expiry must be after issuance'); return x; }
export function validateMaintenanceReceipt(v) { const x = validateSimple(v, 'agentpass.maintenance.receipt', new Set(['schema_version','kind','receipt_id','organization_id','job_id','source_commit','patch_digest','verification_status','created_at','uncertainty']), ['schema_version','kind','receipt_id','organization_id','job_id','source_commit','patch_digest','verification_status','created_at','uncertainty']); timestamp(x.created_at, 'created_at'); if (!['passed','partial','failed','not_run'].includes(x.verification_status)) fail('invalid_receipt', 'verification_status is invalid'); if (!Array.isArray(x.uncertainty) || x.uncertainty.length > 64 || x.uncertainty.some((value) => typeof value !== 'string' || value.length > 256)) fail('invalid_receipt', 'uncertainty must be bounded strings'); return x; }
function validateSimple(v, kind, allowed, required = ['schema_version', 'kind']) { const x = object(v, kind); closed(x, allowed, kind); for (const key of required) if (!Object.hasOwn(x, key)) fail('missing_field', `${kind} is missing a required field`); if (x.schema_version !== 1 || x.kind !== kind) fail('unknown_version', `unsupported ${kind}`); for (const k of ['organization_id','app_id','repository_id','branch','plan_id','grant_id','job_id','policy_id','attestation_id','provider_id','advisory_id','receipt_id']) if (x[k] !== undefined) id(x[k], k); for (const k of ['source_digest','patch_digest']) if (x[k] !== undefined) digest(x[k], k); return x; }

function signatureFreeAdvisory(statement) { const { signature: _signature, ...unsigned } = statement; return unsigned; }
export function signAdvisory(statement, privateKey) { const v = validateAdvisory(statement); return crypto.sign(null, Buffer.from(ADVISORY_SIGNATURE_DOMAIN + '\n' + canonicalJson(signatureFreeAdvisory(v)), 'utf8'), privateKey).toString('base64url'); }
export function verifyAdvisory(statement, signature = statement?.signature, publicKey) { try { const v = validateAdvisory(statement); if (typeof signature !== 'string') return false; return crypto.verify(null, Buffer.from(ADVISORY_SIGNATURE_DOMAIN + '\n' + canonicalJson(signatureFreeAdvisory(v)), 'utf8'), publicKey, Buffer.from(signature, 'base64url')); } catch { return false; } }
export function advisoryDigest(statement) { validateAdvisory(statement); return sha256(ADVISORY_SIGNATURE_DOMAIN + '\n' + canonicalJson(statement)); }
function signatureFreeKeyEvent(statement) { const { signature: _signature, ...unsigned } = statement; return unsigned; }
export function signProviderKeyEvent(statement, privateKey) { const v = validateProviderKeyEvent(statement); return crypto.sign(null, Buffer.from(EVENT_SIGNATURE_DOMAIN + '\n' + canonicalJson(signatureFreeKeyEvent(v)), 'utf8'), privateKey).toString('base64url'); }
export function verifyProviderKeyEvent(statement, signature = statement?.signature, publicKey) { try { const v = validateProviderKeyEvent(statement); if (typeof signature !== 'string') return false; return crypto.verify(null, Buffer.from(EVENT_SIGNATURE_DOMAIN + '\n' + canonicalJson(signatureFreeKeyEvent(v)), 'utf8'), publicKey, Buffer.from(signature, 'base64url')); } catch { return false; } }
